(function(){
'use strict';
const C=window.CurriculumEngine,M=window.MasteryEngine,L=window.LessonPlanner;
if(!C||!M||!L)throw new Error('Core learning services must load before adaptive-engine.js');
function label(state){return C.normalizeState(state).split('_').map(x=>x[0]+x.slice(1).toLowerCase()).join(' ')}
function masteryIcon(state){const s=C.normalizeState(state);return s==='MASTERED'?'✓':s==='NOT_INTRODUCED'?'○':'◐'}
function renderPath(){
 const parent=document.getElementById('parent');if(!parent)return;
 let sec=document.getElementById('learningPath');if(!sec){sec=document.createElement('section');sec.id='learningPath';sec.className='card learning-path-card';parent.querySelector('#skillTracker')?.closest('.card')?.after(sec)}
 const target=L.readinessTarget(window.data||{});const reading=C.skills.filter(s=>s.domain==='reading');
 sec.innerHTML=`<div class="path-head"><div><span class="badge adult">🗺️ Learning Path</span><h3>Reading roadmap</h3></div><small>✓ mastered · ◐ learning · ○ coming next</small></div><div class="path-list">${reading.map(s=>{const st=C.state(s.skill_id,window.data||{});return `<div class="path-row ${target?.skill_id===s.skill_id?'next-target':''}"><span class="path-icon">${masteryIcon(st)}</span><div><b>${s.title}</b><small>${label(st)}${target?.skill_id===s.skill_id?' · Recommended next':''}</small></div></div>`}).join('')}</div>`;
}
function summaryWindow(days){const cut=Date.now()-days*86400000,h=(window.data?.questHistory||[]).filter(x=>new Date((x.date||'1970-01-01')+'T12:00:00').getTime()>=cut),sessions=new Set(h.map(x=>x.date)),bySkill={};h.forEach(x=>{const a=(window.activities||[]).find(v=>v.id===x.activityId);if(!a)return;const k=`${a.domain} · ${a.skill}`;(bySkill[k]||(bySkill[k]=[])).push(x)});const stats=Object.entries(bySkill).map(([k,v])=>({k,n:v.length,avg:v.reduce((n,x)=>n+(Number(x.score)||0),0)/v.length,hints:v.reduce((n,x)=>n+(Number(x.hints)||0),0)/v.length})).sort((a,b)=>b.n-a.n);return{h,sessions,stats}}
function reportText(days){const r=summaryWindow(days);if(!r.h.length)return'No completed learning sessions in this period yet.';const strong=r.stats.filter(x=>x.avg>=.82).slice(0,2),practice=r.stats.filter(x=>x.avg<.72||x.hints>=1.2).slice(0,2),target=L.readinessTarget(window.data||{});return `${r.sessions.size} learning day${r.sessions.size===1?'':'s'} · ${r.h.length} completed activities. ${strong.length?'Strong: '+strong.map(x=>x.k).join(', ')+'. ':''}${practice.length?'Needs practice: '+practice.map(x=>x.k).join(', ')+'. ':''}${target?'Next: '+target.title+'.':''}`}
function renderReports(){const parent=document.getElementById('parent');if(!parent)return;let sec=document.getElementById('parentReports');if(!sec){sec=document.createElement('section');sec.id='parentReports';sec.className='parent-reports';parent.appendChild(sec)}sec.innerHTML=`<div class="section-title"><h2>📈 Progress Reports</h2><p>Actual practice evidence.</p></div><div class="grid thirds"><div class="card compact"><h3>Today</h3><p>${reportText(1)}</p></div><div class="card compact"><h3>This Week</h3><p>${reportText(7)}</p></div><div class="card compact"><h3>This Month</h3><p>${reportText(30)}</p></div></div>`}
function renderWhyNext(){const target=L.readinessTarget(window.data||{}),el=document.getElementById('nextFocus');if(!el)return;if(!target){el.textContent='Sakhi needs a little more practice evidence before choosing the next target.';return}const prereq=target.prerequisites.map(id=>C.byId[id]?.title).filter(Boolean);el.innerHTML=`<b>Working on: ${target.title}</b><br><span>${prereq.length?'Ready because: '+prereq.join(', ')+'.':'This is an appropriate current target.'}</span>`}
function placementNotice(){const parent=document.getElementById('parent');if(!parent||document.getElementById('placementNotice'))return;const answered=Object.keys(window.data?.answers||{}).length;if(answered>=18)return;const box=document.createElement('section');box.id='placementNotice';box.className='card placement-notice';box.innerHTML='<span class="badge adult">🎯 Placement</span><h3>Quick placement check</h3><p>Sakhi will verify strong phonics quickly rather than restarting alphabet work.</p><button class="btn mint" type="button" data-placement-open>Continue placement</button>';box.querySelector('[data-placement-open]').onclick=()=>window.go('baseline');parent.prepend(box)}
function renderParent(){renderPath();renderReports();renderWhyNext();placementNotice()}
window.AdaptiveParentUI=Object.freeze({render:renderParent});
window.UIHooks?.on('navigate',e=>{if(e.args?.[0]==='parent')setTimeout(renderParent,0)});
})();
