(function(){
'use strict';
const P=window.ProgressService;if(!P)throw new Error('progress-service.js must load before backend-bridge.js');
function rerender(){try{window.renderAssessment?.();window.renderLesson?.();window.renderDomains?.();window.renderSkillTracker?.();window.renderRewards?.();window.renderBreakdown?.();window.ensureQuest?.();window.updateStats?.();window.renderNextFocus?.();window.AdaptiveParentUI?.render?.()}catch(e){console.warn('Progress rerender',e)}}
function renderFamilySync(error=''){const parent=document.getElementById('parent');if(!parent)return;let card=document.getElementById('familySyncCard');if(!card){card=document.createElement('div');card.id='familySyncCard';card.className='card family-sync';parent.querySelector('.parent-lock-row')?.after(card)}const status=P.status();if(!status.configured){card.innerHTML='<h3>☁️ Family Progress Sync</h3><p>Cross-device sync is not configured.</p><div class="family-sync-status">Supabase connection details are missing.</div>';return}if(status.remote){card.innerHTML='<h3>☁️ Family Progress Sync</h3><p><b>Connected.</b> Supabase is the durable source of truth for this learner.</p><div class="family-sync-row"><button class="btn soft" data-sync-now>Sync now</button><button class="btn soft" data-sync-out>Disconnect this device</button></div><div class="family-sync-status">Browser storage is only a local cache.</div>';card.querySelector('[data-sync-now]').onclick=()=>P.sync(window.data||{}).then(()=>window.toast?.()).catch(e=>alert(e.message));card.querySelector('[data-sync-out]').onclick=()=>P.signOut().then(()=>location.reload());return}card.innerHTML=`<h3>☁️ Family Progress Sync</h3><p>Use one parent email to keep progress available across family devices.</p><div class="family-sync-row"><input data-sync-email type="email" autocomplete="email" placeholder="Parent email"><button class="btn primary" data-sync-send>Send sign-in link</button></div><div class="family-sync-status">${error?`Sync error: ${error}`:'Existing progress on this device is preserved and migrated after sign-in.'}</div>`;card.querySelector('[data-sync-send]').onclick=async()=>{const email=card.querySelector('[data-sync-email]').value.trim();if(!email)return alert('Enter the parent email.');const state=card.querySelector('.family-sync-status');try{state.textContent='Sending secure sign-in link…';const result=await P.signIn(email);if(result?.error)throw result.error;state.textContent='Check the parent email on this device and open the secure sign-in link.'}catch(e){state.textContent='Could not send sign-in link: '+(e.message||e)}}}
async function boot(){P.installLegacyBridge();renderFamilySync();try{const status=await P.boot(window.data||{});if(status.remote)rerender();renderFamilySync()}catch(e){console.warn('Family sync unavailable',e);renderFamilySync(String(e.message||e))}}
window.FamilySyncUI=Object.freeze({render:renderFamilySync});
window.UIHooks?.on('navigate',e=>{if(e.args?.[0]==='parent')setTimeout(()=>renderFamilySync(),0)});
window.addEventListener('load',boot,{once:true});if(document.readyState==='complete')boot();
})();
