(function(){
'use strict';
const contract=window.ActivityContract;
if(!contract)throw new Error('activity-contract.js must load before challenge-bank.js');
const B=[];
function add(x){B.push({
  character:'Sakhi',character_icon:'✨',icon:'✨',estimated_minutes:3,
  items:[],targets:[],distractors:[],visual_assets:[],audio_assets:[],
  hint_1:'Look carefully and try one part.',hint_2:'Use what you already know.',hint_3:'Sakhi will help with one step.',
  success_feedback:'You solved a stronger challenge!',retry_feedback:'Almost. Use the clue and try again.',
  mastery_signal:'Completes the task accurately with age-appropriate independence.',
  reward:'✨ Thinker Star',phase:'practice',challenge:false,transfer:false,content_tokens:[],...x
});}

add({id:'acc-sounds-mst-sort',domain:'reading',skill:'Beginning sounds',skill_id:'reading.beginning_sounds',difficulty:3,phase:'mixed',interaction_type:'sort',title:'Three-Sound Cloud Sort',objective:'Discriminate /m/, /s/, and /t/ across mixed words.',instruction_text:'Sort by first sound!',spoken_instruction:'Put moon and map with /m/, sun and sock with /s/, and top and tent with /t/.',character_prompt:'Three sound clouds are mixed up!',items:[{id:'moon',label:'Moon',emoji:'🌙'},{id:'map',label:'Map',emoji:'🗺️'},{id:'sun',label:'Sun',emoji:'☀️'},{id:'sock',label:'Sock',emoji:'🧦'},{id:'top',label:'Top',emoji:'🪀'},{id:'tent',label:'Tent',emoji:'⛺'}],targets:[{id:'m',label:'/m/',emoji:'☁️'},{id:'s',label:'/s/',emoji:'☁️'},{id:'t',label:'/t/',emoji:'☁️'}],correct_answer:{moon:'m',map:'m',sun:'s',sock:'s',top:'t',tent:'t'},reason:'Mixed phoneme classification verifies flexible sound knowledge.',content_tokens:['moon','map','sun','sock','top','tent','m','s','t']});
add({id:'acc-sound-position-end',domain:'reading',skill:'Ending sounds',skill_id:'reading.ending_sounds',difficulty:4,phase:'transfer',challenge:true,transfer:true,interaction_type:'tap_choice',title:'Sakhi Sound Detective',objective:'Identify a phoneme by its position in a spoken word.',instruction_text:'What sound ends SUN?',spoken_instruction:'Listen to sun. What tiny sound do you hear at the end?',character_prompt:'Wow! Sakhi has a tricky sound clue for you.',items:[{id:'s',label:'/s/'},{id:'u',label:'short /u/'},{id:'n',label:'/n/'}],correct_answer:'n',distractors:['s','u'],reason:'Changing phoneme position tests transfer beyond predictable beginning-sound tasks.',hint_1:'Stretch the word sun.',hint_2:'Listen to the very last sound.',hint_3:'Sun ends with /n/.',content_tokens:['sun','ending-sound']});
add({id:'acc-cvc-mixed-decode',domain:'reading',skill:'CVC decoding',skill_id:'reading.cvc_decode.mixed',difficulty:3,phase:'mixed',interaction_type:'tap_choice',title:'Mixed Word Gate',objective:'Decode mixed short-vowel CVC words without relying on a predictable word family.',instruction_text:'Read the word SUN!',spoken_instruction:'Touch each sound in sun and read the whole word. Tap sun.',character_prompt:'Open the mixed-word gate!',items:[{id:'sun',label:'sun'},{id:'sit',label:'sit'},{id:'map',label:'map'},{id:'dog',label:'dog'}],correct_answer:'sun',distractors:['sit','map','dog'],reason:'Mixed vowels confirm decoding rather than memorized rhyming patterns.',hint_1:'Start with /s/.',hint_2:'The middle sound is short /u/.',hint_3:'Blend /s/ /u/ /n/: sun.',content_tokens:['sun','sit','map','dog']});
add({id:'acc-cvc-encode-dog',domain:'reading',skill:'CVC encoding',skill_id:'reading.cvc_encode.mixed',difficulty:4,phase:'challenge',challenge:true,interaction_type:'word_builder',title:'Sakhi Spelling Spell',objective:'Encode a mixed CVC word from sound to letters.',instruction_text:'Build DOG!',spoken_instruction:'Listen to dog. Build the word with the letters that match each sound.',character_prompt:'Can you spell this one from the sounds?',items:[{id:'d',label:'d',value:'d'},{id:'o',label:'o',value:'o'},{id:'g',label:'g',value:'g'},{id:'m',label:'m',value:'m'},{id:'t',label:'t',value:'t'}],targets:[{id:'s1',label:'1'},{id:'s2',label:'2'},{id:'s3',label:'3'}],correct_answer:['d','o','g'],distractors:['m','t'],reason:'Encoding reveals phoneme-grapheme gaps that recognition can hide.',hint_1:'Say dog slowly.',hint_2:'The first sound is /d/.',hint_3:'Use d, o, g.',content_tokens:['dog']});
add({id:'acc-phoneme-sequence-sit',domain:'reading',skill:'Phoneme segmentation',skill_id:'reading.segmentation',difficulty:5,phase:'transfer',challenge:true,transfer:true,interaction_type:'word_builder',title:'Sound-to-Word Challenge',objective:'Hear a word, segment its phonemes, and build the full sequence.',instruction_text:'Hear it. Build SIT!',spoken_instruction:'Listen to sit. Think of each tiny sound, then build the word.',character_prompt:'Sakhi has a tricky sound-to-letter challenge!',items:[{id:'s',label:'s',value:'s'},{id:'i',label:'i',value:'i'},{id:'t',label:'t',value:'t'},{id:'a',label:'a',value:'a'},{id:'p',label:'p',value:'p'}],targets:[{id:'s1',label:'1'},{id:'s2',label:'2'},{id:'s3',label:'3'}],correct_answer:['s','i','t'],distractors:['a','p'],reason:'This combines segmentation, sound order, and encoding in one transfer task.',hint_1:'Say sit slowly.',hint_2:'You hear /s/ first.',hint_3:'Use s, i, t.',content_tokens:['sit']});
add({id:'acc-digraph-ship',domain:'reading',skill:'Digraphs',skill_id:'reading.digraphs.sh',difficulty:5,phase:'challenge',challenge:true,interaction_type:'word_builder',title:'Shiny SH Word',objective:'Build a decodable word containing the sh digraph.',instruction_text:'Build SHIP!',spoken_instruction:'Build ship. The first two letters work together to make the /sh/ sound.',character_prompt:'A two-letter sound unlocks this gate!',items:[{id:'s',label:'s',value:'s'},{id:'h',label:'h',value:'h'},{id:'i',label:'i',value:'i'},{id:'p',label:'p',value:'p'},{id:'c',label:'c',value:'c'}],targets:[{id:'s1',label:'1'},{id:'s2',label:'2'},{id:'s3',label:'3'},{id:'s4',label:'4'}],correct_answer:['s','h','i','p'],distractors:['c'],reason:'A digraph increases conceptual phonics complexity rather than simply adding distractors.',hint_1:'Ship starts with /sh/.',hint_2:'The /sh/ sound uses s and h together.',hint_3:'Use s, h, i, p.',content_tokens:['ship','sh']});
add({id:'acc-sentence-order',domain:'reading',skill:'Sentence reading',skill_id:'reading.simple_sentences',difficulty:4,phase:'transfer',challenge:true,transfer:true,interaction_type:'sequence',title:'Build the Tiny Sentence',objective:'Read and order words into a simple decodable sentence.',instruction_text:'Put the sentence in order!',spoken_instruction:'Build this sentence: The cat can sit.',character_prompt:'Make the words sound like a real sentence.',items:[{id:'the',label:'The'},{id:'cat',label:'cat'},{id:'can',label:'can'},{id:'sit',label:'sit'}],targets:[{id:'one',label:'1'},{id:'two',label:'2'},{id:'three',label:'3'},{id:'four',label:'4'}],correct_answer:['the','cat','can','sit'],reason:'Sentence ordering requires decoding plus syntax and meaning.',hint_1:'Which word usually begins this sentence?',hint_2:'Who is the sentence about?',hint_3:'The cat can sit.',content_tokens:['the','cat','can','sit']});
add({id:'acc-story-predict',domain:'reading',skill:'Comprehension',skill_id:'reading.meaning.comprehension',difficulty:4,phase:'transfer',challenge:true,transfer:true,interaction_type:'story_choice',title:'What Happens Next?',objective:'Use story evidence to make a simple prediction.',instruction_text:'What might happen next?',spoken_instruction:'Maya sees dark clouds and carries an umbrella outside. What might happen next?',character_prompt:'Use the clues in the story.',items:[{id:'rain',label:'It may start raining',emoji:'🌧️'},{id:'snow',label:'A snowman appears',emoji:'⛄'},{id:'bed',label:'She falls asleep outside',emoji:'😴'}],correct_answer:'rain',distractors:['snow','bed'],reason:'Prediction develops inference from evidence rather than literal recall.',hint_1:'Think about dark clouds and an umbrella.',hint_2:'What weather often comes with dark clouds?',hint_3:'It may start raining.',content_tokens:['umbrella','dark-clouds','prediction']});

add({id:'acc-math-make5-two-ways',domain:'math',skill:'Number composition',skill_id:'math.compose',difficulty:4,phase:'challenge',challenge:true,interaction_type:'multi_select',title:'Two Ways to Make Five',objective:'Identify multiple valid decompositions of five.',instruction_text:'Pick TWO ways to make 5!',spoken_instruction:'Choose both number pairs that make five.',character_prompt:'Can you find more than one way?',items:[{id:'2+3',label:'2 + 3'},{id:'1+4',label:'1 + 4'},{id:'2+2',label:'2 + 2'},{id:'3+3',label:'3 + 3'}],correct_answer:['2+3','1+4'],distractors:['2+2','3+3'],reason:'Multiple-solution composition builds flexible number sense.',hint_1:'Count each pair.',hint_2:'Two plus three makes five.',hint_3:'2+3 and 1+4 both make 5.',content_tokens:['5','2+3','1+4']});
add({id:'acc-math-missing-to8',domain:'math',skill:'Number bonds',skill_id:'math.number_bonds',difficulty:4,phase:'transfer',challenge:true,transfer:true,interaction_type:'number_manipulative',title:'How Many More to Eight?',objective:'Solve a missing-part problem using manipulatives.',instruction_text:'Make 8 from 5!',spoken_instruction:'There are five gems. Add only the number needed to make eight.',character_prompt:'How many gems are missing?',items:[{id:'g1',label:'Gem',emoji:'💎'},{id:'g2',label:'Gem',emoji:'💎'},{id:'g3',label:'Gem',emoji:'💎'},{id:'g4',label:'Gem',emoji:'💎'},{id:'g5',label:'Gem',emoji:'💎'}],targets:[{id:'crown',label:'Eight-gem crown',emoji:'👑'}],correct_answer:3,initial_count:5,target_total:8,distractors:[1,2,4],reason:'Missing-part structure prepares children for number bonds and subtraction thinking.',hint_1:'Start at five.',hint_2:'Count on: six, seven, eight.',hint_3:'Add three gems.',content_tokens:['5','8','missing-part']});
add({id:'acc-math-subtract6-2',domain:'math',skill:'Subtraction with objects',skill_id:'math.subtraction_objects',difficulty:4,phase:'mixed',interaction_type:'tap_choice',title:'Royal Gem Giveaway',objective:'Reason about taking away from a known quantity.',instruction_text:'6 gems. Give away 2. How many?',spoken_instruction:'The princess has six gems and gives away two. How many are left?',character_prompt:'Think about what stays after two leave.',items:[{id:'4',label:'4'},{id:'3',label:'3'},{id:'8',label:'8'}],correct_answer:'4',distractors:['3','8'],reason:'Subtraction is represented as a meaningful change, not a memorized fact.',hint_1:'Start with six.',hint_2:'Take away one, then one more.',hint_3:'Six take away two leaves four.',content_tokens:['6','2','4','subtraction']});
add({id:'acc-math-multistep8',domain:'math',skill:'Mathematical reasoning',skill_id:'math.multi_step',difficulty:5,phase:'challenge',challenge:true,interaction_type:'tap_choice',title:'Sakhi Gem Puzzle',objective:'Combine known parts and solve the remaining missing quantity.',instruction_text:'How many more gems?',spoken_instruction:'The crown needs eight gems. It already has three blue gems and two purple gems. How many more are needed?',character_prompt:'This one has two thinking steps!',items:[{id:'3',label:'3'},{id:'5',label:'5'},{id:'2',label:'2'}],correct_answer:'3',distractors:['5','2'],reason:'The learner must combine 3 and 2, then compare that total with 8.',hint_1:'First count how many gems are already there.',hint_2:'Three and two make five.',hint_3:'Five needs three more to make eight.',content_tokens:['8','3+2','missing-part']});
add({id:'acc-math-transfer-story5',domain:'math',skill:'Addition with objects',skill_id:'math.addition_objects',difficulty:3,phase:'transfer',transfer:true,interaction_type:'tap_choice',title:'Apple Picnic Addition',objective:'Transfer addition knowledge to a new story context.',instruction_text:'3 apples + 2 apples = ?',spoken_instruction:'There are three apples in one basket and two in another. How many apples altogether?',character_prompt:'Same math, brand-new story!',items:[{id:'5',label:'5 apples',emoji:'🍎'},{id:'4',label:'4 apples',emoji:'🍎'},{id:'6',label:'6 apples',emoji:'🍎'}],correct_answer:'5',distractors:['4','6'],reason:'A new context tests transfer rather than memorization of one visual.',content_tokens:['apples','3+2','5']});

add({id:'acc-logic-abc',domain:'logic',skill:'Pattern recognition',skill_id:'logic.patterns',difficulty:3,phase:'mixed',interaction_type:'tap_choice',title:'ABC Pattern Gate',objective:'Extend an ABC repeating pattern.',instruction_text:'What comes next?',spoken_instruction:'Star, heart, moon, star, heart, moon. What comes next?',character_prompt:'Find the repeating three-part rule.',items:[{id:'star',label:'⭐'},{id:'heart',label:'💖'},{id:'moon',label:'🌙'}],correct_answer:'star',distractors:['heart','moon'],reason:'ABC patterns require tracking a longer repeating unit than AB.',content_tokens:['ABC','star-heart-moon']});
add({id:'acc-logic-aab',domain:'logic',skill:'Pattern recognition',skill_id:'logic.patterns',difficulty:4,phase:'challenge',challenge:true,interaction_type:'tap_choice',title:'AAB Pattern Challenge',objective:'Infer the missing element in an AAB pattern.',instruction_text:'Fill the missing tile!',spoken_instruction:'Star, star, heart, star, star, heart, star, star, what comes next?',character_prompt:'Sakhi has a trickier repeating rule.',items:[{id:'heart',label:'💖'},{id:'star',label:'⭐'},{id:'moon',label:'🌙'}],correct_answer:'heart',distractors:['star','moon'],reason:'AAB structure requires grouping and rule inference.',content_tokens:['AAB','star-star-heart']});
add({id:'acc-logic-rule-explain',domain:'logic',skill:'Simple deduction',skill_id:'logic.deduction',difficulty:4,phase:'transfer',transfer:true,interaction_type:'story_choice',title:'Which Rule Fits?',objective:'Identify the rule that explains a completed pattern.',instruction_text:'Which rule made this?',spoken_instruction:'Look at this pattern: star, heart, heart, star, heart, heart. Which rule fits it?',character_prompt:'Tell Sakhi what rule the builder used.',items:[{id:'abb',label:'One star, then two hearts'},{id:'ab',label:'Star, heart, repeat'},{id:'abc',label:'Three different shapes'}],correct_answer:'abb',distractors:['ab','abc'],reason:'Explaining the underlying rule requires abstraction, not just continuation.',content_tokens:['ABB','explain-rule']});
add({id:'acc-coding-path',domain:'logic',skill:'Coding-style sequencing',skill_id:'logic.coding_sequences',difficulty:5,phase:'challenge',challenge:true,interaction_type:'sequence',title:'Princess Path Code',objective:'Order simple movement commands to reach a destination.',instruction_text:'Build the path code!',spoken_instruction:'The princess must go forward, forward, turn right, then forward. Put the commands in that order.',character_prompt:'Can you debug the castle path?',items:[{id:'f1',label:'Forward',emoji:'⬆️'},{id:'f2',label:'Forward',emoji:'⬆️'},{id:'r',label:'Turn right',emoji:'➡️'},{id:'f3',label:'Forward',emoji:'⬆️'}],targets:[{id:'one',label:'1'},{id:'two',label:'2'},{id:'three',label:'3'},{id:'four',label:'4'}],correct_answer:['f1','f2','r','f3'],reason:'Sequencing commands develops computational thinking without programming syntax.',content_tokens:['forward','right','path-code']});

add({id:'acc-language-cause',domain:'language',skill:'Explaining reasoning',skill_id:'language.cause_effect',difficulty:3,phase:'mixed',interaction_type:'story_choice',title:'Why Did It Happen?',objective:'Identify a simple cause-and-effect relationship.',instruction_text:'Why did the puddle grow?',spoken_instruction:'It rained for a long time and the puddle got bigger. Why did the puddle grow?',character_prompt:'Find the cause in the story.',items:[{id:'rain',label:'More rain added water',emoji:'🌧️'},{id:'book',label:'A book was nearby',emoji:'📕'},{id:'night',label:'It became nighttime',emoji:'🌙'}],correct_answer:'rain',distractors:['book','night'],reason:'Cause/effect requires connecting events rather than recalling a surface detail.',content_tokens:['rain','puddle','cause-effect']});
add({id:'acc-language-inference',domain:'language',skill:'Simple inference',skill_id:'language.inference',difficulty:4,phase:'challenge',challenge:true,interaction_type:'story_choice',title:'Story Clue Detective',objective:'Make a simple inference from clues.',instruction_text:'How might she feel?',spoken_instruction:'Nina practiced a puzzle for a long time. Then she solved it by herself and smiled. How might she feel?',character_prompt:'Use the clues, not just one word.',items:[{id:'proud',label:'Proud',emoji:'😊'},{id:'sleepy',label:'Sleepy',emoji:'😴'},{id:'hungry',label:'Hungry',emoji:'🍎'}],correct_answer:'proud',distractors:['sleepy','hungry'],reason:'Inference combines actions and emotional clues.',content_tokens:['proud','puzzle','inference']});
add({id:'acc-language-mainidea',domain:'language',skill:'Listening comprehension',skill_id:'language.main_idea',difficulty:4,phase:'transfer',transfer:true,interaction_type:'story_choice',title:'What Is This Mostly About?',objective:'Identify the main idea of a short age-appropriate passage.',instruction_text:'What is the story mostly about?',spoken_instruction:'Ava planted a seed, watered it each day, and watched a green sprout grow. What is this mostly about?',character_prompt:'Find the big idea.',items:[{id:'plant',label:'Growing a plant',emoji:'🌱'},{id:'shoes',label:'Buying shoes',emoji:'👟'},{id:'snow',label:'Building a snowman',emoji:'⛄'}],correct_answer:'plant',distractors:['shoes','snow'],reason:'Main-idea selection requires integrating several details.',content_tokens:['seed','sprout','main-idea']});

add({id:'acc-science-float-predict',domain:'science',skill:'Prediction',skill_id:'science.floating_sinking',difficulty:2,phase:'practice',interaction_type:'story_choice',title:'Float or Sink Prediction',objective:'Make a prediction before a simple test.',instruction_text:'What do you predict?',spoken_instruction:'If we put a dry wooden craft stick in water, what do you predict it will do?',character_prompt:'Make your best science prediction.',items:[{id:'float',label:'Float',emoji:'🪵'},{id:'sink',label:'Sink',emoji:'⬇️'},{id:'vanish',label:'Disappear',emoji:'✨'}],correct_answer:'float',distractors:['sink','vanish'],reason:'Prediction encourages scientific thinking before observation.',content_tokens:['wood','float','prediction']});
add({id:'acc-science-shadow',domain:'science',skill:'Testing ideas',skill_id:'science.light',difficulty:3,phase:'transfer',transfer:true,interaction_type:'story_choice',title:'Shadow Thinking',objective:'Reason about how moving a light source can change a shadow.',instruction_text:'What might change?',spoken_instruction:'A flashlight moves closer to a toy. What might happen to the shadow?',character_prompt:'Use what you know about light.',items:[{id:'change',label:'The shadow size can change',emoji:'🔦'},{id:'taste',label:'The toy changes taste',emoji:'😋'},{id:'sing',label:'The toy starts singing',emoji:'🎵'}],correct_answer:'change',distractors:['taste','sing'],reason:'The task asks for a causal prediction about light and shadow.',content_tokens:['flashlight','shadow','prediction']});
add({id:'acc-science-plant-light',domain:'science',skill:'Plants',skill_id:'science.plants',difficulty:3,phase:'challenge',challenge:true,interaction_type:'story_choice',title:'Which Plant Will Grow Better?',objective:'Predict how sunlight affects plant growth.',instruction_text:'Which plant will likely grow better?',spoken_instruction:'Two similar plants get the same water. One gets sunlight and one stays in a dark closet. Which will likely grow better?',character_prompt:'Use the experiment clues.',items:[{id:'sun',label:'The plant with sunlight',emoji:'☀️'},{id:'dark',label:'The plant in the dark',emoji:'🌑'},{id:'same',label:'They must always be exactly the same'}],correct_answer:'sun',distractors:['dark','same'],reason:'The learner reasons from a controlled comparison rather than identifying a plant picture.',content_tokens:['plant','sunlight','experiment']});

add({id:'acc-memory-three',domain:'memory',skill:'3-step directions',skill_id:'memory.three_step',difficulty:3,phase:'mixed',interaction_type:'sequence',title:'Three-Step Moon Mission',objective:'Hold and sequence three spoken directions.',instruction_text:'Moon, star, cloud!',spoken_instruction:'Remember this order: touch the moon, then the star, then the cloud.',character_prompt:'Keep all three in your memory.',items:[{id:'moon',label:'Moon',emoji:'🌙'},{id:'star',label:'Star',emoji:'⭐'},{id:'cloud',label:'Cloud',emoji:'☁️'}],targets:[{id:'one',label:'1'},{id:'two',label:'2'},{id:'three',label:'3'}],correct_answer:['moon','star','cloud'],reason:'Increasing from two to three held items develops working memory capacity.',content_tokens:['moon','star','cloud','3-step']});
add({id:'acc-memory-four',domain:'memory',skill:'Working memory',skill_id:'memory.working_memory',difficulty:4,phase:'challenge',challenge:true,interaction_type:'sequence',title:'Four-Step Memory Spark',objective:'Hold and reproduce a four-item sequence.',instruction_text:'Remember all four!',spoken_instruction:'Remember: moon, star, cloud, heart. Put them in the same order.',character_prompt:'Sakhi has one extra thing to remember.',items:[{id:'moon',label:'Moon',emoji:'🌙'},{id:'star',label:'Star',emoji:'⭐'},{id:'cloud',label:'Cloud',emoji:'☁️'},{id:'heart',label:'Heart',emoji:'💖'}],targets:[{id:'one',label:'1'},{id:'two',label:'2'},{id:'three',label:'3'},{id:'four',label:'4'}],correct_answer:['moon','star','cloud','heart'],reason:'A four-item sequence is a meaningful increase in working-memory demand.',content_tokens:['moon','star','cloud','heart','4-step']});

const accepted=[];
for(const raw of B){
  const check=contract.validate(raw);
  if(!check.ok){window.SakhiRuntimeLog?.log('ADAPTIVE_BANK_INVALID',{activity_id:raw.id,errors:check.errors});continue;}
  const a=check.activity;a.phase=raw.phase;a.challenge=!!raw.challenge;a.transfer=!!raw.transfer;a.content_tokens=raw.content_tokens||[];accepted.push(a);
}
const existing=new Set((window.activities||[]).map(a=>a.id));
for(const a of accepted)if(!existing.has(a.id))window.activities.push(a);
window.SakhiChallengeBank=Object.freeze({activities:accepted.slice(),byId:Object.fromEntries(accepted.map(a=>[a.id,a]))});
window.SakhiRuntimeLog?.log('ADAPTIVE_BANK_READY',{activities:accepted.length});
})();