(function(){
'use strict';
const AUDIO={m:'moon',s:'sun',t:'top',p:'pig',a:'apple',n:'nest',f:'fish',l:'leaf',h:'hat',r:'rainbow'};
function speech(){if(!window.SpeechService)throw new Error('SpeechService unavailable');return window.SpeechService;}
async function playLetterSound(letter){if(!AUDIO[letter])return false;document.querySelectorAll('.sound-orb').forEach(b=>b.classList.toggle('playing',b.dataset.sound===letter));try{return await speech().speakPhoneme(letter)}finally{document.querySelectorAll('.sound-orb').forEach(b=>b.classList.remove('playing'))}}
function addSoundGarden(){const home=document.getElementById('home');if(!home||document.getElementById('soundPlay'))return;const section=document.createElement('section');section.id='soundPlay';section.className='sound-play-card';section.innerHTML=`<div class="sound-head"><div><span class="kid-label">SOUND GARDEN</span><h3>Tap a letter to hear its sound</h3></div><button class="sound-all" type="button">🔊 Play 5</button></div><div class="sound-orbs">${Object.entries(AUDIO).map(([letter,word])=>`<button type="button" class="sound-orb" data-sound="${letter}" aria-label="Hear ${letter} sound"><b>${letter}</b><small>${word}</small><span>🔊</span></button>`).join('')}</div>`;home.appendChild(section);section.querySelectorAll('.sound-orb').forEach(b=>b.addEventListener('click',()=>playLetterSound(b.dataset.sound)));section.querySelector('.sound-all').onclick=async()=>{for(const letter of ['m','s','t','p','a']){await playLetterSound(letter);await new Promise(r=>setTimeout(r,180))}}}
function decorateActivity(event){const [activity,containerId,source]=event.args||[];const host=document.getElementById(containerId),tools=host?.querySelector('.child-tools');if(!activity||!host)return;window.AssetService?.preloadForActivity(activity);if(tools&&!tools.querySelector('.start-over')){const b=document.createElement('button');b.className='child-tool start-over';b.type='button';b.textContent='↻ Start Over';b.onclick=()=>window.ActivityRenderer?.retry();tools.appendChild(b)}setTimeout(()=>speech().speakInstruction(activity.spoken_instruction),20);host.dataset.activitySource=source||'learn'}
function addSuccessActions(){const r=window.interactionRuntime,f=document.getElementById('structuredFeedback');if(!r||!f||f.querySelector('.after-mission-actions'))return;const box=document.createElement('div');box.className='after-mission-actions';box.innerHTML=`<button type="button" class="retry-mission">↻ Play Again</button>${r.source==='quest'?'<button type="button" class="next-mission">Next Adventure →</button>':''}`;f.appendChild(box);box.querySelector('.retry-mission').onclick=()=>window.ActivityRenderer?.retry();const next=box.querySelector('.next-mission');if(next)next.onclick=()=>{const ids=window.data?.quest||[],i=ids.indexOf(r.activity.id),nextId=ids.slice(i+1).find(id=>window.data?.questResults?.[id]==null);window.ActivityRenderer?.close();if(nextId)setTimeout(()=>window.runActivity?.(nextId),80);else window.go?.('quest')}}
function startDomain(domain){window.go?.('learn');setTimeout(()=>window.openDomain?.(domain),20)}
function init(){document.body.classList.add('kid-v5');addSoundGarden();const q=document.getElementById('questSummary');if(q)q.textContent='Listen. Touch. Move. Build. Think. Earn a shiny star!'}
window.playLetterSound=playLetterSound;
window.KidExperience=Object.freeze({playLetterSound,startDomain});
window.UIHooks?.on('activityOpened',decorateActivity);
window.UIHooks?.on('activitySucceeded',()=>setTimeout(addSuccessActions,0));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
