(function(){
'use strict';
const CACHE_KEY='rainbowMagicLearningV2';
const cfg=()=>window.RAINBOW_CONFIG||{};
let client=null,learnerId=null,sessionId=null,ready=false,remote=false,syncTimer=null;
function uuid(){return crypto?.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)});}
function clone(v){return JSON.parse(JSON.stringify(v||{}));}
function mergeUnique(list,key){const m=new Map();for(const x of list||[])m.set(x?.[key]||JSON.stringify(x),x);return [...m.values()];}
function mergeRemote(local,remoteData){if(!remoteData)return local;const out={...local};out.theme=remoteData.profile?.preferred_themes?.[0]||local.theme;out.skills={...(local.skills||{}),...(remoteData.legacySkills||{})};out.evidence={...(local.evidence||{}),...(remoteData.evidence||{})};out.questHistory=mergeUnique([...(local.questHistory||[]),...(remoteData.questHistory||[])],'completion_instance').slice(-250);out.rewardTransactions=mergeUnique([...(local.rewardTransactions||[]),...(remoteData.rewardTransactions||[])],'transaction_id').slice(-500);out.rewardBalances={...(local.rewardBalances||{}),...(remoteData.rewardBalances||{})};if(remoteData.profile?.adaptive_state&&Object.keys(remoteData.profile.adaptive_state).length)out.adaptiveProfile=remoteData.profile.adaptive_state;if(remoteData.profile?.last_session_summary)out.lastAdaptiveSummary=remoteData.profile.last_session_summary;return out;}
async function init(){const c=cfg();if(!c.supabaseUrl||!c.supabaseAnonKey||!window.supabase?.createClient){ready=true;return {remote:false,reason:'not_configured'};}client=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data:{session}}=await client.auth.getSession();remote=!!session;ready=true;if(remote)await ensureProfile();return {remote};}
async function signIn(email){if(!client)await init();if(!client)throw new Error('Backend not configured');return client.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});}
async function signOut(){if(client)await client.auth.signOut();remote=false;learnerId=null;sessionId=null;}
async function ensureProfile(){const {data:{user}}=await client.auth.getUser();if(!user)return null;let {data,error}=await client.from('learner_profiles').select('*').eq('parent_user_id',user.id).order('created_at',{ascending:true}).limit(1).maybeSingle();if(error)throw error;if(!data){const ins=await client.from('learner_profiles').insert({parent_user_id:user.id,display_name:'Learner',birth_year_or_age:'5',current_grade_level:'Pre-K / Kindergarten',preferred_themes:['unicorn'],typical_session_length:20,curriculum_version:window.RainbowCurriculum?.version||'2026.09.07-v1',adaptive_state:{},domain_levels:{},learning_velocity:0}).select('*').single();if(ins.error)throw ins.error;data=ins.data;}learnerId=data.learner_id;return data;}
async function hydrate(localData){if(!remote||!learnerId)return localData;const [profile,skills,attempts,rewards]=await Promise.all([client.from('learner_profiles').select('*').eq('learner_id',learnerId).single(),client.from('learner_skill_progress').select('*').eq('learner_id',learnerId),client.from('learning_attempts').select('*').eq('learner_id',learnerId).order('timestamp',{ascending:true}).limit(500),client.from('reward_transactions').select('*').eq('learner_id',learnerId).order('created_at',{ascending:true}).limit(500)]);if(profile.error||skills.error||attempts.error||rewards.error)throw profile.error||skills.error||attempts.error||rewards.error;const legacySkills={},evidence={},questHistory=[];(skills.data||[]).forEach(s=>{const legacyName=Object.entries(window.RainbowCurriculum?.aliases||{}).find(([,id])=>id===s.skill_id)?.[0]||s.skill_name;legacySkills[`${s.domain}::${legacyName}`]=s.mastery_state.split('_').map(w=>w[0]+w.slice(1).toLowerCase()).join(' ');});(attempts.data||[]).forEach(a=>{const legacyName=Object.entries(window.RainbowCurriculum?.aliases||{}).find(([,id])=>id===a.skill_id)?.[0]||a.skill_id;const key=`${a.domain}::${legacyName}`,score=a.result==='CORRECT'?1:(a.result==='PARTIAL'?0.65:0.3);(evidence[key]||(evidence[key]=[])).push({date:a.timestamp?.slice(0,10),score,activityId:a.activity_id,interaction_type:a.interaction_type,hints:a.hint_level_used,attempts:a.number_of_attempts,independent_success:a.independent_success});questHistory.push({date:a.timestamp?.slice(0,10),activityId:a.activity_id,score,interaction_type:a.interaction_type,hints:a.hint_level_used,attempts:a.number_of_attempts,completion_instance:a.attempt_id});});const rewardTransactions=(rewards.data||[]).map(r=>({...r,status:'SAVED'})),rewardBalances={};for(const r of rewardTransactions)rewardBalances[r.reward_type]=(rewardBalances[r.reward_type]||0)+Number(r.amount||0);return mergeRemote(localData,{profile:profile.data,legacySkills,evidence,questHistory,rewardTransactions,rewardBalances});}
async function beginSession(data){if(!remote||!learnerId)return null;if(sessionId)return sessionId;const r=await client.from('learning_sessions').insert({learner_id:learnerId,theme:data.theme,curriculum_version:window.RainbowCurriculum?.version||'2026.09.07-v1'}).select('session_id').single();if(r.error)throw r.error;sessionId=r.data.session_id;return sessionId;}
function stateFor(skillId,data){const alias=Object.entries(window.RainbowCurriculum?.aliases||{}).find(([,id])=>id===skillId)?.[0];if(!alias)return 'NOT_INTRODUCED';const raw=data.skills?.[`${window.RainbowCurriculum.byId[skillId]?.domain}::${alias}`]||'Not Introduced';return window.RainbowCurriculum.normalizeState(raw);}
async function syncSkills(data){if(!remote||!learnerId)return {saved:false,remote:false};const rows=[];(window.RainbowCurriculum?.skills||[]).forEach(s=>{const state=stateFor(s.skill_id,data),alias=Object.entries(window.RainbowCurriculum.aliases||{}).find(([,id])=>id===s.skill_id)?.[0],ev=alias?(data.evidence?.[`${s.domain}::${alias}`]||[]):[],recent=ev.slice(-10),attemptRecent=(data.activityAttempts||[]).filter(x=>x.skill_id===s.skill_id&&x.save_status==='SAVED').slice(-10),avg=recent.length?recent.reduce((n,x)=>n+(+x.score||0),0)/recent.length:attemptRecent.length?attemptRecent.reduce((n,x)=>n+(+x.score||0),0)/attemptRecent.length:0,independent=attemptRecent.filter(x=>x.independent_success).length,count=Math.max(recent.length,attemptRecent.length),lastDate=attemptRecent.at(-1)?.completed_at||(recent.length?`${recent[recent.length-1].date}T12:00:00Z`:null);rows.push({learner_id:learnerId,domain:s.domain,subdomain:s.stage,skill_id:s.skill_id,skill_name:s.title,skill_level:s.difficulty_level,mastery_state:state,mastery_score:avg,confidence_score:Math.min(1,count/5),independent_accuracy:attemptRecent.length?independent/attemptRecent.length:0,attempt_count:count,independent_correct_count:independent,last_practiced_at:lastDate,difficulty_level:data.adaptiveProfile?.skills?.[s.skill_id]?.difficulty||s.difficulty_level});});if(rows.length){const q=await client.from('learner_skill_progress').upsert(rows,{onConflict:'learner_id,skill_id'});if(q.error)throw q.error;}return {saved:true,remote:true};}
async function appendAttempt(evt,activity){if(!remote||!learnerId||!evt||!activity)return {saved:false,remote:false};const sid=await beginSession(window.data||{}),skillId=activity.skill_id||window.RainbowCurriculum?.aliases?.[activity.skill]||`${activity.domain}.${String(activity.skill).toLowerCase().replace(/[^a-z0-9]+/g,'_')}`,result=evt.type==='success'?'CORRECT':evt.type==='not_yet'?'INCORRECT':'PARTIAL';const q=await client.from('learning_attempts').upsert({attempt_id:evt.event_id||uuid(),learner_id:learnerId,session_id:sid,activity_id:activity.id,domain:activity.domain,skill_id:skillId,interaction_type:activity.interaction_type||activity.type||'offline_activity',difficulty:activity.difficulty||1,question_or_task_id:activity.id,expected_answer:activity.correct_answer??null,learner_response:evt.learner_response??null,result,hint_level_used:evt.hintLevel||0,number_of_attempts:evt.attempts||1,response_time_ms:evt.elapsed?evt.elapsed*1000:null,completed:true,timestamp:evt.timestamp||new Date().toISOString(),curriculum_version:window.RainbowCurriculum?.version||'2026.09.07-v1',independent_success:evt.type==='success'&&(evt.attempts||1)<=1&&(evt.hintLevel||0)===0,completion_quality:evt.completion_quality??evt.score??null,challenge_mode:!!activity.challenge,curriculum_level:activity.difficulty||1,adaptive_decision:{phase:activity.phase||'practice',transfer:!!activity.transfer}},{onConflict:'attempt_id'});if(q.error)throw q.error;return {saved:true,remote:true,attempt_id:evt.event_id};}
async function appendRewardTransaction(tx){if(!remote||!learnerId||!tx)return {saved:false,remote:false};const sid=await beginSession(window.data||{});const q=await client.from('reward_transactions').upsert({transaction_id:tx.transaction_id||uuid(),learner_id:learnerId,session_id:sid,activity_id:tx.activity_id,reward_type:tx.reward_type,amount:tx.amount||1,reason:tx.reason,idempotency_key:tx.idempotency_key,created_at:tx.created_at||new Date().toISOString()},{onConflict:'learner_id,idempotency_key'});if(q.error)throw q.error;return {saved:true,remote:true};}
async function completeSession(summary){if(!remote||!learnerId)return {saved:false,remote:false};const sid=sessionId||await beginSession(window.data||{});const q=await client.from('learning_sessions').update({completed_at:summary.completed_at||new Date().toISOString(),duration:summary.duration||null,skills_practiced:summary.skills_practiced||[],activities_completed:(summary.completed_activities||[]).length,reward_earned:{transaction_ids:summary.reward_transaction_ids||[]},session_summary:window.AdaptiveAccelerationService?.buildDailySummary?.()||null}).eq('session_id',sid);if(q.error)throw q.error;sessionId=null;return {saved:true,remote:true};}
async function syncSnapshot(data){if(!remote||!learnerId)return {saved:false,remote:false};const adaptive=data.adaptiveProfile||{},domainLevels={};for(const [domain,x] of Object.entries(adaptive.domains||{}))domainLevels[domain]={difficulty:x.difficulty,current_skill_id:x.current_skill_id,ready_next:x.ready_next,stretch_skill:x.stretch_skill};const p=await client.from('learner_profiles').update({preferred_themes:[data.theme||'unicorn'],last_activity_at:new Date().toISOString(),curriculum_version:window.RainbowCurriculum?.version||'2026.09.07-v1',adaptive_state:adaptive,domain_levels:domainLevels,learning_velocity:Number(adaptive.learningVelocity||0),last_session_summary:adaptive.lastSummary||null}).eq('learner_id',learnerId);if(p.error)throw p.error;await syncSkills(data);return {saved:true,remote:true};}
function queueSync(data){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncSnapshot(clone(data)).catch(console.warn),600);}
function backendStatus(){return {ready,remote,learnerId,sessionId,configured:!!(cfg().supabaseUrl&&cfg().supabaseAnonKey)};}
window.RainbowPersistence={init,hydrate,signIn,signOut,ensureProfile,beginSession,appendAttempt,appendRewardTransaction,completeSession,queueSync,syncSnapshot,backendStatus,uuid,CACHE_KEY};
})();