(function(){
'use strict';
var Cur=SakhiCurriculum,Prog=SakhiProgress,Plan=SakhiPlan,Adaptive=SakhiAdaptive,Trails=SakhiTrails,Pres=SakhiPresentation,Act=SakhiActivities,Audio=SakhiAudio,Tpl=SakhiTemplates,Cloud=SakhiCloud;
var $=function(s){return document.querySelector(s);};
var view='home',plan=null,session=null,missionIndex=0,current=null,qIndex=0,answers=[],controller=null,hintLevel=0,parentOpen=false,questionTries=0,questionStartedAt=Date.now(),awaitingNext=false,transitioning=false,activityCompleted=false,narrationRun=0,launching=false,answerLocked=false,advanceTimer=null,preparedMissions={},adventureMode=localStorage.getItem('sakhi_adventure_mode')==='princess'?'princess':'unicorn';
var RUN_KEY='sakhi.v3.active-adventure';
function saveRun(nextIndex,nextCurrent){try{if(!plan||!session)return;var savedCurrent=arguments.length>1?nextCurrent:current;localStorage.setItem(RUN_KEY,JSON.stringify({savedAt:Date.now(),plan:plan,session:session,missionIndex:typeof nextIndex==='number'?nextIndex:missionIndex,current:savedCurrent,qIndex:savedCurrent?qIndex:0,answers:savedCurrent?answers:[],hintLevel:savedCurrent?hintLevel:0,questionTries:savedCurrent?questionTries:0}));}catch(e){}}
function clearRun(){try{localStorage.removeItem(RUN_KEY);}catch(e){}}
function loadRun(){try{var r=JSON.parse(localStorage.getItem(RUN_KEY)||'null');if(!r||!r.plan||!r.session||Date.now()-r.savedAt>7*86400000){clearRun();return false;}plan=r.plan;session=r.session;missionIndex=Number(r.missionIndex)||0;current=r.current||null;qIndex=Number(r.qIndex)||0;answers=Array.isArray(r.answers)?r.answers:[];hintLevel=Number(r.hintLevel)||0;questionTries=Number(r.questionTries)||0;return true;}catch(e){clearRun();return false;}}
function toast(m){var t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(function(){t.classList.remove('show');},2600);}
function setWorld(domain){if(domain)document.body.dataset.domain=domain;else delete document.body.dataset.domain;}
function clearAdvance(){if(advanceTimer){clearTimeout(advanceTimer);advanceTimer=null;}}
function missionSeed(m,index){var evidence=Prog.evidence(m.pick.skill_id);return[plan.date,plan.program_day,index,evidence.attempt_count||0].join(':');}
function prepareMission(index){if(!plan||index<0||index>=plan.missions.length)return Promise.resolve(null);if(preparedMissions[index])return Promise.resolve(preparedMissions[index]);var m=plan.missions[index],a=Act.generate(m.pick.skill_id,m.pick.band,missionSeed(m,index),Prog.recentQuestionKeys?Prog.recentQuestionKeys(m.pick.skill_id):[]);a._mission=m;preparedMissions[index]=a;return Audio.prefetchActivity(a).catch(function(e){console.warn('[Sakhi] Mission prefetch',e&&e.message||e);}).then(function(){return a;});}
function beginMissionAudio(){var activity=current,question=q();if(!activity||!question)return;var first=Audio.prefetch(question),cue=Audio.playTransitionCue?Audio.playTransitionCue():Promise.resolve(false);Promise.all([cue.catch(function(){return false;}),first.catch(function(){return false;})]).then(function(){if(current===activity&&qIndex===0)speak();});Audio.prefetchActivity(activity).then(function(){if(current===activity)prepareMission(missionIndex+1);}).catch(function(){});}
function show(v){clearAdvance();Audio.stopAll();view=v;document.body.dataset.view=v;if(v!=='activity')setWorld(null);document.querySelectorAll('.view').forEach(function(n){n.classList.toggle('active',n.dataset.view===v);});document.querySelectorAll('[data-nav]').forEach(function(b){b.classList.toggle('active',b.dataset.nav===v);});render();window.scrollTo(0,0);}
function setAdventureMode(mode){adventureMode=mode;localStorage.setItem('sakhi_adventure_mode',adventureMode);document.body.dataset.adventureMode=adventureMode;if(view==='activity'&&current)renderActivity();else renderHome();}
function render(){renderStats();if(view==='home')renderHome();else if(view==='map')renderMap();else if(view==='rewards')renderRewards();else if(view==='parent')renderParent();else if(view==='activity')renderActivity();}
function renderStats(){var n=$('#starStat');if(n)n.textContent='✦ '+Prog.stars();}
function setVoicePreparation(open,message,progress){var box=$('#voicePrepare'),copy=$('#voicePrepareStatus'),bar=$('#voicePrepareBar');if(!box)return;box.classList.toggle('show',!!open);box.setAttribute('aria-hidden',open?'false':'true');if(copy&&message)copy.textContent=message;if(bar)bar.style.width=Math.max(2,Math.min(100,progress||2))+'%';}
async function ensureVoiceReady(){
  if(!Audio.isEnabled())return true;
  if(!await Audio.unlock())throw new Error('Sound permission was blocked.');
  var st=Audio.status();if(st.naturalState==='ready')return true;
  setVoicePreparation(true,'Connecting to Sakhi’s Kokoro voice…',st.naturalProgress||2);
  var timer=setInterval(function(){var s=Audio.status(),p=s.naturalProgress||2;setVoicePreparation(true,p>=100?'Sakhi is ready!':'Preparing Kokoro af_heart · '+p+'%',p);},350);
  try{await Audio.prepare();setVoicePreparation(true,'Sakhi is ready!',100);await new Promise(function(resolve){setTimeout(resolve,280);});return true;}
  finally{clearInterval(timer);setVoicePreparation(false,'',0);}
}
function trailCard(d){var p=Prog.domainProgress(d.domain_id),t=Trails.get(d.domain_id);return '<article class="trail-card domain-'+d.domain_id+'" data-trail-domain="'+d.domain_id+'" role="button" tabindex="0" aria-label="Open '+t.name+' trail"><div class="mini-scene">'+Pres.scene(d.domain_id,p)+'</div><div class="trail-card-copy"><h3>'+t.icon+' '+t.name+'</h3><p>'+d.title+' · '+Trails.chapter(d.domain_id,p)+'</p><div class="meter" aria-label="'+p+' percent explored"><i style="width:'+p+'%"></i></div><small>'+p+'% explored</small><span class="trail-open">Open trail →</span></div></article>';}
function renderHome(){
  setWorld(null);if(!session||!plan){plan=Plan.build();preparedMissions={};}prepareMission(0);
  document.body.dataset.adventureMode=adventureMode;$('#homeHero').innerHTML=Pres.scene('reading',Prog.domainProgress('reading'),adventureMode==='princess'?'princess':'home');
  $('#modeUnicorn').classList.toggle('active',adventureMode==='unicorn');$('#modePrincess').classList.toggle('active',adventureMode==='princess');$('#heroTitle').innerHTML=adventureMode==='unicorn'?'<span class="desktop-title">Your next<br>adventure<br>starts with a little<br>magic.</span><span class="mobile-title">Ready for a<br>little magic?</span>':'<span class="desktop-title">A little courage.<br>A kingdom of<br>possibilities.</span><span class="mobile-title">A kingdom of<br>possibilities.</span>';$('#heroInvite').textContent=adventureMode==='unicorn'?'Luna saved a place for you. Shall we explore?':'Your crown is curiosity. Come and discover something wonderful.';
  $('#todayTitle').textContent='Day '+plan.program_day+' · '+plan.missions.length+' magical missions';
  var names=plan.missions.map(function(m){var s=Cur.skill(m.pick.skill_id);return s?s.title:m.pick.skill_id;});
  $('#todaySummary').textContent=names.join(' • ')+' • one hands-on mission';
  $('#questCount').textContent=plan.missions.length+' little quests + a hands-on discovery';$('#todayPath').innerHTML=names.map(function(name,i){return '<span><i>'+(i+1)+'</i><b>'+name+'</b></span>';}).join('')+'<span><i>✦</i><b>Play away from the screen</b></span>';
  $('#startBtn').textContent=session?'Continue my adventure →':"Let's play →";
  var order=['reading','math','writing','language','science','logic','wellbeing','creative'],domains=Cur.domains();
  var grid=$('#trailPreview');grid.innerHTML=order.map(function(id){return domains.find(function(d){return d.domain_id===id;});}).filter(Boolean).map(trailCard).join('');
}
function renderMap(){var g=$('#mapGrid');g.innerHTML=Cur.domains().map(function(d){return trailCard(d);}).join('');}
async function startTrail(domain){if(launching)return;launching=true;try{Audio.unlock().catch(function(){});var daily=Plan.build(),idx=daily.missions.findIndex(function(m){var s=Cur.skill(m.pick.skill_id);return s&&s.domain_id===domain;});if(idx<0){var pick=Adaptive.pick(domain,[]);if(!pick)throw new Error('No available skill for '+domain);daily={date:daily.date,program_day:daily.program_day,minutes:daily.minutes,missions:[{domain:domain,minutes:Math.max(5,daily.minutes-5),pick:pick}],offscreen:{minutes:5,domain:domain,prompt:'Show a grown-up one thing you discovered on this trail.'},celebration_minutes:daily.celebration_minutes};idx=0;}if(session)Prog.endSession(session.session_id,'LEFT_EARLY');plan=daily;preparedMissions={};session=Prog.startSession(plan);missionIndex=idx;await loadMission();}catch(e){console.error('[Sakhi trail]',e);toast('That trail could not open. Tap once more to try again.');}finally{launching=false;}}
function renderRewards(){var s=Prog.load();$('#rewardTotal').textContent=Prog.stars();var box=$('#rewardRecent'),recent=s.rewards.slice(-10).reverse();box.innerHTML=recent.length?recent.map(function(r){var sk=Cur.skill(r.skill_id);return '<div class="reward-row"><span>⭐ +'+r.amount+' '+r.label+'</span><span class="muted">'+(sk?sk.title:'practice')+'</span></div>';}).join(''):'<p class="center muted">Complete an adventure to collect your first Trail Stars.</p>';}
function parentMetric(label,value,sub){return '<article class="parent-card"><small>'+label+'</small><h2>'+value+'</h2><p class="muted">'+sub+'</p></article>';}
function parentCurriculumPicker(){var domains=Cur.domains(),domainOptions=domains.map(function(d){return'<option value="'+d.domain_id+'">'+d.title+'</option>';}).join(''),skillOptions=domains.map(function(d){return Cur.skillsIn(d.domain_id).map(function(sk,i){var chapter=Math.min(4,Math.floor(i/Math.max(1,Math.ceil(Cur.skillsIn(d.domain_id).length/5)))),chapterName=Trails.get(d.domain_id).chapters[chapter];return'<option data-domain="'+d.domain_id+'" value="'+sk.skill_id+'">'+chapterName+' · '+sk.title+'</option>';}).join('');}).join('');return'<section class="parent-card parent-section curriculum-control"><small>CURRICULUM CONTROL</small><h2>Choose exactly what comes next</h2><p>Select a subject and lesson, or move to the next scheduled day. This changes the learning path without pretending a skipped skill was mastered.</p><div class="curriculum-picker"><label>Subject<select id="curriculumDomain">'+domainOptions+'</select></label><label>Chapter & lesson<select id="curriculumSkill">'+skillOptions+'</select></label></div><div class="parent-form"><button class="primary" id="startChosenLesson">Start selected lesson</button><button class="soft" id="advanceProgramDay">Finish today and open the next day</button></div><p class="muted">Daily plans always include Reading, Math, and Writing, followed by one rotating discovery subject.</p></section>';}
async function startParentLesson(skillId){var sk=Cur.skill(skillId);if(!sk)return;if(session)Prog.endSession(session.session_id,'LEFT_EARLY');var pick={skill_id:sk.skill_id,band:Prog.bandFor(sk.skill_id),reason:'selected by parent'},base=Plan.build();plan={date:base.date,program_day:base.program_day,minutes:Math.max(10,Number(Prog.load().settings.session_minutes)||30),missions:[{domain:sk.domain_id,minutes:10,pick:pick}],offscreen:{minutes:5,domain:sk.domain_id,prompt:'Show a grown-up one new thing you learned in '+sk.title+'.'},celebration_minutes:2};preparedMissions={};session=Prog.startSession(plan);missionIndex=0;clearRun();saveRun();await loadMission();}
async function advanceProgramDay(){if(session)Prog.endSession(session.session_id,'COMPLETED');session=null;current=null;clearRun();plan=Plan.build();preparedMissions={};session=Prog.startSession(plan);missionIndex=0;saveRun();await loadMission();}
async function renderParent(){
  if(!parentOpen){$('#parentGate').hidden=false;$('#parentBody').hidden=true;return;}
  $('#parentGate').hidden=true;var s=Prog.load(),body=$('#parentBody'),ins=Prog.insights(),cloud=Cloud.state(),audio=await Audio.phonemeReport(),today=Plan.build(),nowPick=today.missions[0]&&today.missions[0].pick,nextPick=today.missions[1]&&today.missions[1].pick,skillTitle=function(id){var x=Cur.skill(id);return x?x.title:'Ready to explore';};body.hidden=false;
  var strengths=ins.strengths.length?ins.strengths.map(function(e){return skillTitle(e.skill_id)+' · '+Math.round((e.last_accuracy||0)*100)+'%';}).join('<br>'):'Complete a few activities to reveal strengths.';
  var needs=ins.needs.length?ins.needs.map(function(e){return skillTitle(e.skill_id)+' · '+(e.mastery_state||'learning').toLowerCase().replace(/_/g,' ');}).join('<br>'):'No targeted review is due yet.';
  body.innerHTML='<div class="parent-grid">'+parentMetric('This week',ins.week.sessions+' sessions',ins.week.minutes+' minutes · '+ins.week.activities+' activities')+parentMetric('Accuracy',ins.week.accuracy===null?'—':ins.week.accuracy+'%',ins.week.independence===null?'No objective answers yet':ins.week.independence+'% independent')+parentMetric('Skills mastered',ins.mastered,ins.reviewDue+' review'+(ins.reviewDue===1?'':'s')+' due')+parentMetric('Progress safety',cloud.status==='CONNECTED'?'Synced':'On this device',cloud.status==='CONNECTED'?(cloud.email||'Parent account'):'Sign in for cross-device restore')+'</div>'+
  '<section class="parent-card parent-section today-focus"><small>TODAY’S GOAL</small><h2>'+skillTitle(nowPick&&nowPick.skill_id)+'</h2><p>'+((nowPick&&Adaptive.explain(nowPick))||'A balanced confidence-building session.')+'</p><div class="journey"><span><b>PAST</b>Foundations practiced</span><span class="current"><b>CURRENT</b>'+skillTitle(nowPick&&nowPick.skill_id)+'</span><span><b>NEXT</b>'+skillTitle(nextPick&&nextPick.skill_id)+'</span><span><b>LATER</b>Transfer to stories and real-world problems</span></div></section>'+
  '<div class="parent-two"><section class="parent-card parent-section"><h2>What the evidence says</h2><h3>Growing strengths</h3><p>'+strengths+'</p><h3>Needs the next lesson</h3><p>'+needs+'</p></section><section class="parent-card parent-section"><h2>Last 7 days by subject</h2>'+ins.domains.map(function(d){return '<div class="parent-progress"><p><b>'+d.title+'</b><span>'+(d.accuracy===null?'No activity yet':d.accuracy+'% accuracy · challenge '+d.band)+'</span></p><div class="meter"><i style="width:'+d.progress+'%"></i></div></div>';}).join('')+'</section></div>'+
  parentCurriculumPicker()+
  '<section class="parent-card parent-section"><h2>Family account & history</h2>'+(cloud.configured?(cloud.status==='CONNECTED'?'<p class="sync-good">✓ Signed in as <b>'+cloud.email+'</b>. Progress restores on another device after sign-in.</p><div class="parent-form"><button class="soft" id="cloudSync">Sync now</button><button class="soft" id="cloudSignOut">Sign out</button></div>':'<p>Progress is always preserved on this device. Create or sign in to a free parent account for cross-device backup and restore.</p><div class="parent-form"><input class="parent-input" id="cloudEmail" type="email" autocomplete="email" placeholder="Parent email"><input class="parent-input" id="cloudPassword" type="password" autocomplete="current-password" minlength="6" placeholder="Password (6+ characters)"><button class="soft" id="cloudSignIn">Sign in</button><button class="soft" id="cloudSignUp">Create account</button></div>'):'<p class="muted">Account sync is not configured in this build; local history still remains on this device.</p>')+'</section>'+
  '<section class="parent-card parent-section"><h2>Audio readiness</h2><p class="audio-badge good">Kokoro af_heart · persistent fast cache enabled</p><p class="muted">The complete instruction and choices are prefetched and reused across visits. Phonics uses real-word sound anchors to improve pronunciation; verified recordings are used when installed.</p><div class="audio-tools"><button class="soft" id="testVoiceBtn">🔊 Test Sakhi voice</button><span class="muted" id="audioStatusText"></span></div></section>'+
  '<section class="parent-card parent-section"><h2>Learning settings</h2><label class="parent-setting">Learner name <input class="parent-input" id="learnerName" maxlength="30" value="'+String(s.learner.name||'Sakhi').replace(/"/g,'&quot;')+'"></label><label class="parent-setting"><input type="checkbox" id="voiceToggle" '+(Audio.isEnabled()?'checked':'')+'> Spoken instructions</label><label class="parent-setting">Challenge <select id="challengeMode"><option value="AUTO">Automatically adapt</option><option value="MORE">More challenge</option><option value="GENTLE">Gentler steps</option></select></label><label class="parent-setting">Session length <select id="sessionMinutes"><option value="20">20 min</option><option value="25">25 min</option><option value="30">30 min</option></select></label><button class="soft" id="exportBtn">Export progress backup</button></section>';
  var sm=$('#sessionMinutes');sm.value=String(s.settings.session_minutes||30);sm.onchange=function(){Prog.setSetting('session_minutes',Number(sm.value));toast('Session length saved');};
  var domainSelect=$('#curriculumDomain'),skillSelect=$('#curriculumSkill');function filterCurriculum(){var domain=domainSelect.value,first=null;Array.from(skillSelect.options).forEach(function(o){var visible=o.dataset.domain===domain;o.hidden=!visible;if(visible&&!first)first=o;});if(first)skillSelect.value=first.value;}domainSelect.onchange=filterCurriculum;filterCurriculum();$('#startChosenLesson').onclick=function(){startParentLesson(skillSelect.value).catch(function(e){console.error(e);toast('That lesson could not start.');});};$('#advanceProgramDay').onclick=function(){advanceProgramDay().catch(function(e){console.error(e);toast('The next learning day could not start.');});};
  var cm=$('#challengeMode');cm.value=s.settings.challenge||'AUTO';cm.onchange=function(){Prog.setSetting('challenge',cm.value);toast('Challenge preference saved');};$('#learnerName').onchange=function(e){Prog.setLearnerName(e.target.value);toast('Learner name saved');};
  $('#voiceToggle').onchange=function(e){Audio.setEnabled(e.target.checked);Prog.setSetting('voice',e.target.checked);};
  if($('#testVoiceBtn'))$('#testVoiceBtn').onclick=async function(){var out=$('#audioStatusText');out.textContent='Preparing the real Sakhi voice…';try{await ensureVoiceReady();out.textContent='✨ Kokoro Sakhi voice is ready.';await Audio.speak('Hello! Sakhi voice is ready for our learning adventure.');}catch(e){out.textContent='Sakhi voice could not load. Check the connection and try again.';}};
  if($('#cloudSignIn'))$('#cloudSignIn').onclick=async function(){try{await Cloud.signIn($('#cloudEmail').value,$('#cloudPassword').value);await Prog.syncCloud();toast('History restored and synced');renderParent();renderStats();}catch(e){console.error(e);toast(e.message||'Could not sign in.');}};
  if($('#cloudSignUp'))$('#cloudSignUp').onclick=async function(){try{var r=await Cloud.signUp($('#cloudEmail').value,$('#cloudPassword').value);if(r.needsConfirmation)toast('Check your email to confirm the account');else{await Prog.syncCloud();toast('Account created and progress synced');renderParent();}}catch(e){console.error(e);toast(e.message||'Could not create account.');}};
  if($('#cloudSync'))$('#cloudSync').onclick=async function(){try{await Prog.syncCloud();toast('History is up to date');renderParent();renderStats();}catch(e){toast('Sync paused. Your device copy is safe.');}};
  if($('#cloudSignOut'))$('#cloudSignOut').onclick=async function(){await Cloud.signOut();toast('Family progress disconnected');renderParent();};
  $('#exportBtn').onclick=function(){var blob=new Blob([JSON.stringify(Prog.snapshot(),null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='sakhi-progress-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(u);};
}
async function start(){
  $('#startBtn').disabled=true;
  try{Audio.unlock().catch(function(){});if(session&&plan){if(missionIndex>plan.missions.length){Prog.endSession(session.session_id);session=null;clearRun();show('rewards');}else if(current){show('activity');beginMissionAudio();}else await loadMission();return;}plan=Plan.build();preparedMissions={};session=Prog.startSession(plan);missionIndex=0;saveRun();await loadMission();}
  catch(e){console.error('[Sakhi start]',e);toast('The adventure could not open. Tap once more to try again.');}
  finally{$('#startBtn').disabled=false;}
}
async function loadMission(){
  if(missionIndex>=plan.missions.length)return offscreenMission();
  var m=plan.missions[missionIndex],prepared=preparedMissions[missionIndex];current=prepared||Act.generate(m.pick.skill_id,m.pick.band,missionSeed(m,missionIndex),Prog.recentQuestionKeys?Prog.recentQuestionKeys(m.pick.skill_id):[]);current.activity_id=m.pick.skill_id+':'+m.pick.band+':'+session.session_id+':'+missionIndex;current._mission=m;qIndex=0;answers=[];hintLevel=0;questionTries=0;saveRun();show('activity');beginMissionAudio();
}
function offscreenMission(){
  current={skill_id:'creative.imaginative_play',skill_title:'Hands-on mission',domain_id:plan.offscreen.domain,band:1,band_name:'PRACTICE',evidence_mode:'practice',questions:[{template:'practice',prompt:plan.offscreen.prompt,narration:plan.offscreen.prompt,answer:'done',evidence_mode:'practice',hints:['A grown-up can join you.']}]};
  current._mission={domain:plan.offscreen.domain,minutes:plan.offscreen.minutes,pick:{skill_id:current.skill_id,reason:'off-screen practice'}};qIndex=0;answers=[];hintLevel=0;questionTries=0;saveRun();show('activity');beginMissionAudio();return Promise.resolve();
}
function q(){return current.questions[qIndex];}
async function speak(){var run=++narrationRun,pill=$('#voicePill'),button=$('#hearBtn');if(pill)pill.textContent='✨ Sakhi voice';if(button)button.setAttribute('aria-busy','true');try{await Audio.narrate(q());}catch(e){if(run===narrationRun&&e.kind!=='DISABLED'){console.warn('[Sakhi voice]',e);if(pill)pill.textContent='🔊 Hear again';toast('Sakhi voice could not play. Tap Hear again.');}}finally{if(run===narrationRun&&button)button.removeAttribute('aria-busy');}}
function renderActivity(){
  if(!current)return;var d=current.domain_id,p=Prog.domainProgress(d),t=Trails.get(d),cue=Pres.storyCue(d,current.skill_title,qIndex);setWorld(d);
  clearAdvance();answerLocked=false;activityCompleted=false;$('#activityTrail').textContent=t.name;$('#activitySkill').textContent=current.skill_title;$('#activityProgress').textContent=(missionIndex+1)+' of '+(plan.missions.length+1)+' quests';$('#activityScene').innerHTML=Pres.scene(d,p,{kind:'activity',skill:current.skill_title,template:q().template,question:qIndex});$('#missionEyebrow').textContent=t.companion;$('#missionStory').textContent=cue.text||'Take your time. I’m right here.';$('#missionStep').textContent=cue.step;$('#questLabel').textContent=current.evidence_mode==='practice'?'A little practice':'A little discovery';$('#questionPrompt').textContent=q().prompt;$('#hintArea').textContent=hintLevel?(q().hints||[]).slice(0,hintLevel).map(function(h){return'💡 '+h;}).join('  '):'';$('#checkBtn').textContent='Check ✓';awaitingNext=false;
  questionStartedAt=Date.now();controller=Tpl.render($('#interaction'),q(),{domain:d,onProgress:function(){if(controller)$('#checkBtn').disabled=!controller.isReady();}});$('#checkBtn').disabled=!controller.isReady();$('#hintBtn').disabled=!(q().hints||[]).length;
}
function hint(){var h=q().hints||[];if(hintLevel<h.length){hintLevel++;saveRun();$('#hintArea').textContent=h.slice(0,hintLevel).map(function(x){return'💡 '+x;}).join('  ');Audio.speak(h[hintLevel-1]).catch(function(){});}if(hintLevel>=h.length)$('#hintBtn').disabled=true;}
function check(){
  if(awaitingNext){clearAdvance();awaitingNext=false;nextQuestion();return;}
  if(answerLocked||!controller)return;var r=controller.check();if(!r)return;questionTries++;
  if(!r.correct&&current.evidence_mode!=='practice'&&questionTries<2){toast('Good try — here is a clue.');if(hintLevel<(q().hints||[]).length)hint();setTimeout(function(){controller.reset();$('#checkBtn').disabled=true;},500);return;}
  answers.push({correct:r.correct,hintsUsed:hintLevel,response:r.response,tries:questionTries,response_ms:Math.max(0,Date.now()-questionStartedAt)});saveRun();
  $('#hintArea').textContent=r.correct?'You found it! Ready for the next little adventure?':'We’ll practice that one again later.';$('#hintBtn').disabled=true;$('#checkBtn').disabled=false;$('#checkBtn').textContent='Next discovery →';awaitingNext=true;answerLocked=true;advanceTimer=setTimeout(function(){advanceTimer=null;if(awaitingNext){awaitingNext=false;nextQuestion();}},700);
}
function nextQuestion(){clearAdvance();if(qIndex<current.questions.length-1){qIndex++;hintLevel=0;questionTries=0;awaitingNext=false;saveRun();renderActivity();speak();}else finishActivity();}
function finishActivity(){
  clearAdvance();if(activityCompleted)return;activityCompleted=true;
  var result=Prog.completeActivity({activity:current,sessionId:session.session_id,answers:answers});saveRun(missionIndex+1,null);renderStats();var t=Trails.get(current.domain_id),amount=result.rewards_issued.length?result.rewards_issued[0].amount:0;$('#celebrateIcon').innerHTML='<img src="'+(window.SAKHI_ICON_DATA||'./icon-192.png')+'" alt="">';$('#celebrateTitle').textContent=current.skill_title+' complete!';$('#celebrateBody').textContent=t.companion+' is cheering for you.';$('#celebrateReward').textContent='✦ '+amount+' trail stars earned';var finalMission=missionIndex>=plan.missions.length;$('#continueBtn').textContent=finalMission?'See my treasures →':'Next little adventure →';$('#celebrate').classList.add('show');
  var rewardMedia=Pres.mediaFor&&Pres.mediaFor(current.domain_id,current.skill_title,q().template,qIndex);if(rewardMedia)$('#celebrateIcon').innerHTML='<img src="'+rewardMedia.src+'" alt="'+rewardMedia.alt+'">';
}
async function continueAfter(){
  var button=$('#continueBtn'),overlay=$('#celebrate');if(transitioning||!overlay.classList.contains('show'))return;transitioning=true;var previousIndex=missionIndex;
  button.disabled=true;button.setAttribute('aria-busy','true');Audio.stopAll();narrationRun++;overlay.classList.remove('show');
  try{
    missionIndex=previousIndex+1;
    if(missionIndex>plan.missions.length){if(session)Prog.endSession(session.session_id);session=null;current=null;clearRun();show('rewards');}
    else{await loadMission();if(missionIndex===previousIndex)throw new Error('Adventure did not advance');window.scrollTo(0,0);}
  }catch(e){console.error('[Sakhi next adventure]',e);missionIndex=previousIndex;saveRun();overlay.classList.add('show');toast('That adventure paused. Tap once more to continue.');}
  finally{transitioning=false;button.disabled=false;button.removeAttribute('aria-busy');}
}
function bind(){
  document.querySelectorAll('[data-nav]').forEach(function(b){b.onclick=function(){show(b.dataset.nav);};});document.addEventListener('click',function(e){var card=e.target.closest&&e.target.closest('[data-trail-domain]');if(card)startTrail(card.dataset.trailDomain);});document.addEventListener('keydown',function(e){var card=e.target.closest&&e.target.closest('[data-trail-domain]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();startTrail(card.dataset.trailDomain);}});$('#startBtn').onclick=start;$('#modeUnicorn').onclick=function(){setAdventureMode('unicorn');};$('#modePrincess').onclick=function(){setAdventureMode('princess');};$('#quitBtn').onclick=function(){if(session)Prog.endSession(session.session_id,'LEFT_EARLY');session=null;show('home');};$('#hearBtn').onclick=async function(){try{await ensureVoiceReady();await speak();}catch(e){console.warn('[Sakhi repeat]',e);toast('Sakhi voice could not play. Check the connection and try again.');}};$('#hintBtn').onclick=hint;$('#checkBtn').onclick=check;$('#continueBtn').onclick=continueAfter;$('#gateBtn').onclick=function(){var answer=String($('#gateAnswer').value||'').replace(/\s/g,'');if(answer==='071621'){parentOpen=true;$('#gateAnswer').value='';renderParent();}else toast('Try the grown-up question again. That passcode did not match.');};Audio.onFault(function(e){console.warn('[Sakhi audio]',e.kind,e.message);});
  $('#quitBtn').addEventListener('click',function(){current=null;clearRun();});
}
function bootFailure(e){
  console.error('[Sakhi boot failed]',e);window.__SAKHI_BOOT_ERROR=String(e&&e.message||e);var box=$('#bootFallback');if(box){box.hidden=false;var detail=box.querySelector('[data-boot-detail]');if(detail)detail.textContent='Build '+(window.SAKHI_BUILD_ID||'unknown')+' · '+window.__SAKHI_BOOT_ERROR;}
}
async function boot(){
  loadRun();
  try{await Cur.load();Prog.load();Audio.setEnabled(Prog.load().settings.voice!==false);bind();if(Cloud&&Cloud.probe){await Cloud.probe().catch(function(e){console.warn('Cloud probe',e.message);});if(Cloud.state().status==='CONNECTED')await Prog.syncCloud().catch(function(e){console.warn('History sync',e.message);});}renderHome();renderStats();if(Audio.isEnabled()&&Audio.warm)Audio.warm().catch(function(e){console.warn('[Sakhi] Voice warm-up',e&&e.message||e);});window.__SAKHI_BOOTED=true;document.documentElement.classList.add('sakhi-ready');if('serviceWorker'in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('./sw.js?v=4.1.0',{updateViaCache:'none'}).then(function(r){r.update().catch(function(){});}).catch(function(e){console.warn('SW',e.message);});}}
  catch(e){bootFailure(e);}
}
window.SakhiApp={boot:boot,show:show};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
