(function(){
'use strict';
const auth=window.ParentAuthService;if(!auth)throw new Error('parent-auth-service.js must load before sakhi-shell.js');
function ensureParentGate(){if(document.getElementById('parentGate'))return;const gate=document.createElement('div');gate.id='parentGate';gate.className='parent-gate hidden';gate.innerHTML=`<div class="parent-gate-card" role="dialog" aria-modal="true" aria-labelledby="parentGateTitle"><button class="parent-close" type="button" aria-label="Close">×</button><div class="parent-lock-icon">🔒</div><h2 id="parentGateTitle">Parents only</h2><p>Enter your parent passcode.</p><input id="parentPasscode" inputmode="numeric" autocomplete="off" maxlength="6" type="password" aria-label="Parent passcode" placeholder="••••••"><button id="parentUnlockBtn" class="btn primary" type="button">Unlock</button><div id="parentGateMsg" class="parent-gate-msg" aria-live="polite"></div></div>`;document.body.appendChild(gate);const close=()=>{gate.classList.add('hidden');gate.querySelector('#parentPasscode').value='';gate.querySelector('#parentGateMsg').textContent=''};gate.querySelector('.parent-close').onclick=close;gate.addEventListener('click',e=>{if(e.target===gate)close()});gate.querySelector('#parentUnlockBtn').onclick=async()=>{const input=gate.querySelector('#parentPasscode'),msg=gate.querySelector('#parentGateMsg');if(!input.value.trim()){msg.textContent='Enter the passcode.';return}if(!await auth.unlock(input.value.trim())){msg.textContent='That passcode did not match.';input.select();return}close();window.go?.('parent')};gate.querySelector('#parentPasscode').addEventListener('keydown',e=>{if(e.key==='Enter')gate.querySelector('#parentUnlockBtn').click()})}
function openParentGate(){ensureParentGate();const gate=document.getElementById('parentGate');gate.classList.remove('hidden');setTimeout(()=>gate.querySelector('#parentPasscode')?.focus(),20)}
function ensureFamilySyncCard(){const parent=document.getElementById('parent');if(!parent||document.getElementById('familySyncCard'))return;const card=document.createElement('div');card.id='familySyncCard';card.className='card family-sync sakhi-family-sync';card.innerHTML='<h3>☁️ Family Progress Sync</h3><p>Checking your secure family connection…</p><div class="family-sync-status">Please wait a moment.</div>';parent.querySelector('.parent-lock-row')?.after(card)}
function simplifyHome(){const home=document.getElementById('home');if(!home)return;home.classList.add('sakhi-home');home.querySelectorAll('.section-title,.grid,.priority-grid,.scene-gallery').forEach(el=>el.classList.add('sakhi-secondary-content'));let intro=document.getElementById('sakhiChildHome');if(intro)return;intro=document.createElement('section');intro.id='sakhiChildHome';intro.className='sakhi-child-home';intro.innerHTML=`<div class="sakhi-guide"><div class="sakhi-avatar" aria-hidden="true">✨</div><div><span class="sakhi-kicker">SAKHI MAGIC LEARNING</span><h2>Ready for today's magical adventure?</h2><p>Listen, touch, move, build, discover.</p></div></div><button class="sakhi-start" type="button">🌈 START TODAY'S ADVENTURE</button><div class="sakhi-kingdoms"><button data-kind="reading"><span>📚</span><b>Story Castle</b></button><button data-kind="math"><span>🔢</span><b>Number Kingdom</b></button><button data-kind="logic"><span>🧩</span><b>Puzzle Palace</b></button><button data-kind="science"><span>🔬</span><b>Discovery World</b></button><button data-kind="creativity"><span>🎨</span><b>Create & Play</b></button></div>`;home.prepend(intro);intro.querySelector('.sakhi-start').onclick=()=>window.go?.('quest');intro.querySelectorAll('[data-kind]').forEach(button=>button.onclick=()=>{window.go?.('learn');setTimeout(()=>window.openDomain?.(button.dataset.kind),20)})}
function rebrand(){document.title='Sakhi Magic Learning';const apple=document.querySelector('meta[name="apple-mobile-web-app-title"]');if(apple)apple.content='Sakhi Magic Learning';document.querySelectorAll('.nav [data-go="parent"],.bottom [data-go="parent"]').forEach(b=>{b.innerHTML=b.closest('.bottom')?'<span>🔒</span>Parents':'🔒 Parents'});const parentTitle=document.querySelector('#parent .section-title h2');if(parentTitle)parentTitle.textContent='🔒 Parents'}
function installGuard(){window.UIHooks?.on('beforeNavigate',event=>{if(event.args?.[0]!=='parent')return true;if(auth.isUnlocked()){auth.touch();return true}openParentGate();return false})}
function init(){rebrand();ensureParentGate();ensureFamilySyncCard();simplifyHome();installGuard()}
window.openParentGate=openParentGate;window.lockSakhiParent=()=>{auth.lock();window.go?.('home')};
window.addEventListener('sakhi-parent-auth-required',openParentGate);window.addEventListener('sakhi-parent-auth-expired',()=>{if(document.getElementById('parent')?.classList.contains('active'))window.go?.('home')});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
