(function(){
'use strict';
var Cur=SakhiCurriculum,Prog=SakhiProgress,Plan=SakhiPlan,Adaptive=SakhiAdaptive,Trails=SakhiTrails,Pres=SakhiPresentation,Act=SakhiActivities,Audio=SakhiAudio,Tpl=SakhiTemplates,Cloud=SakhiCloud;
var $=function(s){return document.querySelector(s);};
var view='home',plan=null,session=null,missionIndex=0,current=null,qIndex=0,answers=[],controller=null,hintLevel=0,parentOpen=false,questionTries=0,questionStartedAt=Date.now(),awaitingNext=false,transitioning=false,activityCompleted=false,narrationRun=0,launching=false,answerLocked=false,advanceTimer=null,nextQuestionReady=Promise.resolve(),preparedMissions={},preparedTrails={},trailWarmQueue=Promise.resolve(),adventureMode=localStorage.getItem('sakhi_adventure_mode')==='princess'?'princess':'unicorn';
var RUN_KEY='sakhi.v3.active-adventure';
function saveRun(nextIndex,nextCurrent){try{if(!plan||!session)return;var savedCurrent=arguments.length>1?nextCurrent:current,r={savedAt:Date.now(),plan:plan,session:session,missionIndex:typeof nextIndex==='number'?nextIndex:missionIndex,current:savedCurrent,qIndex:savedCurrent?qIndex:0,answers:savedCurrent?answers:[],hintLevel:savedCurrent?hintLevel:0,questionTries:savedCurrent?questionTries:0,awaitingNext:savedCurrent?awaitingNext:false};localStorage.setItem(RUN_KEY,JSON.stringify(r));if(Prog.setActiveRun)Prog.setActiveRun(r);}catch(e){}}
function clearRun(){try{localStorage.removeItem(RUN_KEY);if(Prog.clearActiveRun)Prog.clearActiveRun();}catch(e){}}
function loadRun(){try{var r=Prog.getActiveRun&&Prog.getActiveRun()||JSON.parse(localStorage.getItem(RUN_KEY)||'null');if(!r||!r.plan||!Array.isArray(r.plan.missions)||!r.session)return false;plan=r.plan;session=r.session;missionIndex=Math.max(0,Number(r.missionIndex)||0);current=r.current&&Array.isArray(r.current.questions)?r.current:null;qIndex=current?Math.max(0,Math.min(current.questions.length-1,Number(r.qIndex)||0)):0;answers=Array.isArray(r.answers)?r.answers:[];hintLevel=Math.max(0,Number(r.hintLevel)||0);questionTries=Math.max(0,Number(r.questionTries)||0);awaitingNext=!!r.awaitingNext;return true;}catch(e){return false;}}
function toast(m){var t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(function(){t.classList.remove('show');},2600);}
function setWorld(domain){if(domain)document.body.dataset.domain=domain;else delete document.body.dataset.domain;}
function clearAdvance(){if(advanceTimer){clearTimeout(advanceTimer);advanceTimer=null;}}
function missionSeed(m,index){var evidence=Prog.evidence(m.pick.skill_id);return[plan.date,plan.program_day,index,evidence.attempt_count||0].join(':');}
function resolveMission(index){if(!plan||index<0||index>=plan.missions.length)return null;var m=plan.missions[index];if(m.pick)return m;var used=plan.missions.slice(0,index).map(function(x){return x.pick&&x.pick.skill_id;}).filter(Boolean),pick=Adaptive.pick(m.domain,used);if(!pick)return null;m.pick=pick;m.dynamic=false;return m;}
function prepareMission(index,allowDynamic){if(!plan||index<0||index>=plan.missions.length)return Promise.resolve(null);if(preparedMissions[index])return Promise.resolve(preparedMissions[index]);var m=plan.missions[index];if(!m.pick&&!allowDynamic)return Promise.resolve(null);m=resolveMission(index);if(!m||!m.pick)return Promise.resolve(null);var a=Act.generate(m.pick.skill_id,m.pick.band,missionSeed(m,index),Prog.recentQuestionKeys?Prog.recentQuestionKeys(m.pick.skill_id):[]);a._mission=m;preparedMissions[index]=a;return Audio.prefetchActivity(a).catch(function(e){console.warn('[Sakhi] Mission prefetch',e&&e.message||e);}).then(function(){return a;});}
function beginMissionAudio(){var activity=current,question=q(),pill=$('#voicePill');if(!activity||!question)return;if(pill)pill.textContent='✨ Sakhi voice';speak(false);Audio.prefetchActivity(activity).then(function(){if(current===activity&&plan.missions[missionIndex+1]&&plan.missions[missionIndex+1].pick)prepareMission(missionIndex+1);}).catch(function(){});}
function show(v){clearAdvance();Audio.stopAll();view=v;document.body.dataset.view=v;if(v!=='activity')setWorld(null);document.querySelectorAll('.view').forEach(function(n){n.classList.toggle('active',n.dataset.view===v);});document.querySelectorAll('[data-nav]').forEach(function(b){b.classList.toggle('active',b.dataset.nav===v);});render();window.scrollTo(0,0);}
function setAdventureMode(mode){adventureMode=mode;localStorage.setItem('sakhi_adventure_mode',adventureMode);document.body.dataset.adventureMode=adventureMode;if(view==='activity'&&current)renderActivity();else renderHome();}
function render(){renderStats();if(view==='home')renderHome();else if(view==='map')renderMap();else if(view==='rewards')renderRewards();else if(view==='parent')renderParent();else if(view==='activity')renderActivity();}
function renderStats(){var n=$('#starStat');if(n)n.textContent='✦ '+Prog.stars();}
function setVoicePreparation(open,message,progress){var box=$('#voicePrepare'),copy=$('#voicePrepareStatus'),bar=$('#voicePrepareBar');if(!box)return;box.classList.toggle('show',!!open);box.setAttribute('aria-hidden',open?'false':'true');if(copy&&message)copy.textContent=message;if(bar)bar.style.width=Math.max(2,Math.min(100,progress||2))+'%';}
async function ensureVoiceReady(){
  if(!Audio.isEnabled())return true;
  if(!await Audio.unlock())throw new Error('Sound permission was blocked.');
  var st=Audio.status();if(st.naturalState==='ready')return true;
  setVoicePreparation(true,'Opening Sakhi’s instant voice pack…',st.naturalProgress||2);
  var timer=setInterval(function(){var s=Audio.status(),p=s.naturalProgress||2;setVoicePreparation(true,p>=100?'Sakhi is ready!':'Opening local narration · '+p+'%',p);},350);
  try{await Audio.prepare();setVoicePreparation(true,'Sakhi is ready!',100);await new Promise(function(resolve){setTimeout(resolve,280);});return true;}
  finally{clearInterval(timer);setVoicePreparation(false,'',0);}
}
function goalForSkill(sk){if(!sk)return'Ready for a short placement activity.';var goals={print:'Track print from left to right.',letter_name:'Identify the requested letter.',rhyme:'Recognize words with matching ending sounds.',syllable:'Count spoken word parts.',initial_sound:'Match a beginning sound to its letter.',final_sound:'Identify the last sound in a word.',oral_blend:'Blend separate sounds into a word.',oral_segment:'Count and separate sounds in a word.',short_vowel:'Identify the middle vowel sound.',cvc_read:'Read a three-sound word.',cvc_spell:'Build a three-sound word in order.',phoneme_change:'Change one sound to build a new word.',word_family:'Use a familiar spelling pattern to read a new word.',sentence_meaning:'Read a sentence and use its exact meaning.',nonfiction:'Find information in a short factual passage.',morphology:'Use word endings and meaningful word parts.',count_sequence:'Complete and reason about number sequences.',numeral:'Recognize written numbers.',count:'Count objects accurately once each.',subitize:'Recognize a small quantity without recounting.',compare:'Compare two numbers or quantities.',compose:'Find a missing part of a number.',add:'Combine groups and solve an addition problem.',sub:'Take away and find what remains.',bond:'Complete a number bond.',teen:'Build numbers with tens and ones.',pattern:'Extend a repeating pattern.',measure:'Compare length from a shared starting point.',shape:'Identify a shape by its properties.',data:'Read and compare simple data.',skip_count:'Use equal jumps of 2, 5, or 10.',unknown:'Reason backward to find a missing number.',word_problem:'Choose and solve the operation in a story.',ordinal:'Identify position in an ordered set.',measure_reason:'Measure fairly and compare units.',shape_compose:'Build and break apart shapes.',data_reason:'Use graph data to solve a new question.',edit_sentence:'Edit capitals, spacing, and punctuation.',sentence_expand:'Add a useful detail to a sentence.',opinion_write:'State an opinion and support it with a reason.',informative_write:'Write connected facts or steps to teach.',details:'Recall and connect details from spoken text.',compare_ideas:'Explain an important similarity or difference.',oral_reasoning:'Give a relevant how or why explanation.',analogy:'Use a relationship to complete an analogy.',constraints:'Combine several clues to solve one puzzle.',life_cycle:'Order and compare stages in a life cycle.',force:'Reason about pushes, pulls, gravity, and friction.',senses:'Choose safe senses for careful observation.',earth_material:'Compare soil, rocks, sand, and water.',problem_solving:'Choose a fair, flexible social solution.',self_management:'Plan, focus, and check work independently.',music_pattern:'Hear and continue a rhythm pattern.',design_challenge:'Plan, test, and improve a working design.'};return goals[sk.kind]||('Complete a guided '+sk.title.toLowerCase()+' task with clear steps.');}
function outcomeForSkill(sk){var goals={biology_living:'Use evidence to decide what is living and what it needs.',animal_groups:'Classify animals by observable features and explain why.',animal_diets:'Compare herbivores, carnivores, and omnivores using their food.',food_chain:'Trace how energy moves from the Sun through a simple food chain.',body_systems:'Connect body parts and systems to the jobs they do.',astronomy:'Use day-and-night observations to reason about the sky safely.',solar_system:'Compare the Sun, Moon, Earth, and nearby planets.',ecosystems:'Explain how living things depend on a habitat.',past_present:'Use clues to tell whether something belongs to the past or present.',family_history:'Put personal and family events in a meaningful time order.',history_compare:'Compare everyday life across two times using evidence.',maps_globes:'Use maps, globes, symbols, and directions to describe a place.',landmarks:'Connect important places with the stories communities remember.',inventions:'Explain how a tool or invention changed a daily task.',cultures:'Notice similarities and differences in traditions respectfully.',citizenship:'Choose responsible actions that help a classroom or community.'};return sk&&(goals[sk.kind]||goalForSkill(sk))||goalForSkill(sk);}
function firstTrailPick(domain){var s=Prog.load(),seen=(s.attempts||[]).filter(function(a){return a.domain_id===domain&&a.objective;});if(!seen.length){var placement={reading:'reading.short_vowels',math:'math.compare',writing:'writing.cvc_words',language:'language.listening',logic:'logic.patterns',science:'science.observe',wellbeing:'wellbeing.emotions',creative:'creative.imaginative_play',world:'world.past_present'}[domain],sk=Cur.skill(placement);if(sk)return{skill_id:sk.skill_id,band:Math.max(2,Prog.bandFor(sk.skill_id)),reason:'subject placement assessment',placement:true};}return Adaptive.pick(domain,[]);}
function wrapUpFor(domain){return SakhiWrapUps.forDomain(domain);}
function trailCard(d){var p=Prog.domainProgress(d.domain_id),t=Trails.get(d.domain_id),pick=firstTrailPick(d.domain_id),sk=pick&&Cur.skill(pick.skill_id),mode=pick&&pick.placement?'Placement assessment':'Next lesson';return '<article class="trail-card domain-'+d.domain_id+'" data-trail-domain="'+d.domain_id+'" role="button" tabindex="0" aria-label="Open '+t.name+' trail"><div class="mini-scene">'+Pres.scene(d.domain_id,p)+'</div><div class="trail-card-copy"><h3>'+t.icon+' '+t.name+'</h3><p class="trail-chapter">'+d.title+' · '+Trails.chapter(d.domain_id,p)+'</p><div class="trail-next"><small>'+mode+'</small><b>'+(sk?sk.title:'Ready to explore')+'</b><span>'+outcomeForSkill(sk)+'</span></div><div class="meter" aria-label="'+p+' percent explored"><i style="width:'+p+'%"></i></div><div class="trail-meta"><small>'+p+'% explored</small><span class="trail-open">Open trail →</span></div></div></article>';}
function trailPlan(domain){var base=Plan.build(),s=Prog.load(),seen=(s.attempts||[]).filter(function(a){return a.domain_id===domain&&a.objective;}),ids=[];if(!seen.length&&domain==='math')ids=['math.compare','math.addition_5','math.cardinality_20'];else if(!seen.length&&domain==='reading')ids=['reading.short_vowels','reading.cvc_mixed','reading.oral_blending'];else{var first=firstTrailPick(domain);if(first)ids=[first.skill_id];}var missions=ids.map(function(id){return{domain:domain,minutes:5,pick:{skill_id:id,band:Math.max(2,Prog.bandFor(id)),reason:seen.length?'best next lesson':'subject placement assessment',placement:!seen.length}};}).filter(function(m){return!!Cur.skill(m.pick.skill_id);});while(missions.length<4&&missions.length)missions.push({domain:domain,minutes:5,pick:null,dynamic:true});var wrap=wrapUpFor(domain);return{date:base.date,program_day:base.program_day,minutes:Math.max(20,Number(s.settings.session_minutes)||30),trail_domain:domain,missions:missions,offscreen:{minutes:5,domain:domain,prompt:wrap.prompt},celebration_minutes:2};}
function prewarmTrail(domain){if(preparedTrails[domain])return preparedTrails[domain].promise;var planForTrail=trailPlan(domain),m=planForTrail.missions[0];if(!m)return Promise.resolve(null);var a=Act.generate(m.pick.skill_id,m.pick.band,['trail',domain,Prog.evidence(m.pick.skill_id).attempt_count||0].join(':'),Prog.recentQuestionKeys?Prog.recentQuestionKeys(m.pick.skill_id):[]);a._mission=m;var promise=Audio.prefetchActivity(a).catch(function(){return false;}).then(function(){return a;});preparedTrails[domain]={plan:planForTrail,activity:a,promise:promise};return promise;}
function warmVisibleTrails(){Cur.domains().forEach(function(d){trailWarmQueue=trailWarmQueue.then(function(){return prewarmTrail(d.domain_id);});});}
function renderHome(){
  setWorld(null);if(!session||!plan){plan=Plan.build();preparedMissions={};}prepareMission(0).then(function(){return prewarmTrail('math');}).catch(function(){});
  document.body.dataset.adventureMode=adventureMode;$('#homeHero').innerHTML=Pres.scene('reading',Prog.domainProgress('reading'),adventureMode==='princess'?'princess':'home');
  $('#modeUnicorn').classList.toggle('active',adventureMode==='unicorn');$('#modePrincess').classList.toggle('active',adventureMode==='princess');$('#heroTitle').innerHTML=adventureMode==='unicorn'?'<span class="desktop-title">Your next<br>adventure<br>starts with a little<br>magic.</span><span class="mobile-title">Ready for a<br>little magic?</span>':'<span class="desktop-title">A little courage.<br>A kingdom of<br>possibilities.</span><span class="mobile-title">A kingdom of<br>possibilities.</span>';$('#heroInvite').textContent=adventureMode==='unicorn'?'Luna saved a place for you. Shall we explore?':'Your crown is curiosity. Come and discover something wonderful.';
  $('#todayTitle').textContent='Day '+plan.program_day+' · '+plan.missions.length+' magical missions';
  var names=plan.missions.map(function(m){var s=Cur.skill(m.pick.skill_id),title=s?s.title:m.pick.skill_id;return(m.focus?m.focus+': ':'')+title;});
  $('#todaySummary').textContent=names.join(' • ')+' • one hands-on mission';
  $('#questCount').textContent=plan.missions.length+' little quests + a hands-on discovery';$('#todayPath').innerHTML=names.map(function(name,i){return '<span><i>'+(i+1)+'</i><b>'+name+'</b></span>';}).join('')+'<span><i>✦</i><b>Play away from the screen</b></span>';
  $('#startBtn').textContent=session?'Continue my adventure →':"Let's play →";
  var order=['math','science','language','reading','world','logic','wellbeing','writing','creative'],domains=Cur.domains();
  var grid=$('#trailPreview');grid.innerHTML=order.map(function(id){return domains.find(function(d){return d.domain_id===id;});}).filter(Boolean).map(trailCard).join('');
}
function renderMap(){var g=$('#mapGrid');g.innerHTML=Cur.domains().map(function(d){return trailCard(d);}).join('');warmVisibleTrails();}
async function startTrail(domain){if(launching)return;launching=true;try{Audio.unlock().catch(function(){});var warm=preparedTrails[domain],daily=warm&&warm.plan||trailPlan(domain);if(!daily.missions.length)throw new Error('No available skill for '+domain);if(session)Prog.endSession(session.session_id,'LEFT_EARLY');plan=daily;preparedMissions={};if(warm&&warm.activity)preparedMissions[0]=warm.activity;session=Prog.startSession(plan);missionIndex=0;await loadMission();}catch(e){console.error('[Sakhi trail]',e);toast('That trail could not open. Tap once more to try again.');}finally{launching=false;}}
function renderRewards(){var s=Prog.load();$('#rewardTotal').textContent=Prog.stars();var box=$('#rewardRecent'),recent=s.rewards.slice(-10).reverse();box.innerHTML=recent.length?recent.map(function(r){var sk=Cur.skill(r.skill_id);return '<div class="reward-row"><span>⭐ +'+r.amount+' '+r.label+'</span><span class="muted">'+(sk?sk.title:'practice')+'</span></div>';}).join(''):'<p class="center muted">Complete an adventure to collect your first Trail Stars.</p>';}
function parentMetric(label,value,sub){return '<article class="parent-card"><small>'+label+'</small><h2>'+value+'</h2><p class="muted">'+sub+'</p></article>';}
function parentCurriculumPicker(){var domains=Cur.domains(),domainOptions=domains.map(function(d){return'<option value="'+d.domain_id+'">'+d.title+'</option>';}).join(''),skillOptions=domains.map(function(d){return Cur.skillsIn(d.domain_id).map(function(sk,i){var chapter=Math.min(4,Math.floor(i/Math.max(1,Math.ceil(Cur.skillsIn(d.domain_id).length/5)))),chapterName=Trails.get(d.domain_id).chapters[chapter],stage=sk.difficulty_level>=5?'Stretch / Grade 1 bridge':sk.difficulty_level>=3?'Kindergarten build':'Foundation';return'<option data-domain="'+d.domain_id+'" value="'+sk.skill_id+'">'+stage+' · '+chapterName+' · '+sk.title+'</option>';}).join('');}).join('');return'<section class="parent-card parent-section curriculum-control"><small>CURRICULUM CONTROL</small><h2>Choose exactly what comes next</h2><p>Select a subject and lesson, including the new Kindergarten Build and Grade 1 Bridge work, or move to the next scheduled day. This changes the learning path without pretending a skipped skill was mastered.</p><div class="curriculum-picker"><label>Subject<select id="curriculumDomain">'+domainOptions+'</select></label><label>Stage, chapter & lesson<select id="curriculumSkill">'+skillOptions+'</select></label></div><div class="parent-form"><button class="primary" id="startChosenLesson">Start selected lesson</button><button class="soft" id="advanceProgramDay">Finish today and open the next day</button></div><p class="muted">Automatic mode uses placement evidence, prerequisite readiness, varied practice, and spaced review. Parent choice remains available at any time.</p></section>';}
async function startParentLesson(skillId){var sk=Cur.skill(skillId);if(!sk)return;if(session)Prog.endSession(session.session_id,'LEFT_EARLY');var pick={skill_id:sk.skill_id,band:Prog.bandFor(sk.skill_id),reason:'selected by parent'},base=Plan.build(),wrap=wrapUpFor(sk.domain_id);plan={date:base.date,program_day:base.program_day,minutes:Math.max(10,Number(Prog.load().settings.session_minutes)||30),missions:[{domain:sk.domain_id,minutes:10,pick:pick}],offscreen:{minutes:5,domain:sk.domain_id,prompt:wrap.prompt},celebration_minutes:2};preparedMissions={};session=Prog.startSession(plan);missionIndex=0;clearRun();saveRun();await loadMission();}
async function advanceProgramDay(){if(session)Prog.endSession(session.session_id,'COMPLETED');session=null;current=null;clearRun();plan=Plan.build();preparedMissions={};session=Prog.startSession(plan);missionIndex=0;saveRun();await loadMission();}
async function renderParent(){
  if(!parentOpen){$('#parentGate').hidden=false;$('#parentBody').hidden=true;return;}
  $('#parentGate').hidden=true;var s=Prog.load(),body=$('#parentBody'),ins=Prog.insights(),cloud=Cloud.state(),audio=await Audio.phonemeReport(),today=Plan.build(),run=Prog.getActiveRun&&Prog.getActiveRun(),nowPick=today.missions[0]&&today.missions[0].pick,nextPick=today.missions[1]&&today.missions[1].pick,skillTitle=function(id){var x=Cur.skill(id);return x?x.title:'Ready to explore';};body.hidden=false;
  var signalName=function(x){return{SECURE:'Secure',LIKELY_KNOWS:'Likely knows',DEVELOPING:'Developing',NEEDS_SUPPORT:'Needs support',INSUFFICIENT_EVIDENCE:'Not checked yet'}[x]||x;};
  var strengths=ins.strengths.length?ins.strengths.map(function(e){return'<b>'+skillTitle(e.skill_id)+'</b> · '+signalName(e.signal)+' · '+e.accuracy+'% accuracy · '+e.independence+'% independent · '+e.confidence.toLowerCase()+' confidence';}).join('<br>'):'Complete a few objective activities to reveal strengths.';
  var needs=ins.needs.length?ins.needs.map(function(e){return'<b>'+skillTitle(e.skill_id)+'</b> · '+signalName(e.signal)+' · '+e.accuracy+'% accuracy · '+e.hints+' hints';}).join('<br>'):'No skill currently has enough evidence to require targeted support.';
  var resume=run&&run.current?'<p><b>'+skillTitle(run.current.skill_id)+'</b> · question '+(Number(run.qIndex||0)+1)+' of '+((run.current.questions||[]).length||1)+'</p><p class="muted">The exact activity, answers, hints, and curriculum position are stored with the learner history.</p>':'<p class="muted">No unfinished activity. The next session will begin from the saved curriculum position.</p>';
  var recentRows=ins.recent.length?ins.recent.map(function(a){var sk=Cur.skill(a.skill_id),date=new Date(a.at).toLocaleDateString(),score=a.objective?(a.correct_questions+'/'+a.total_questions+' correct'):'guided practice completed';return'<div class="history-row"><div><b>'+(sk?sk.title:a.skill_id)+'</b><span>'+outcomeForSkill(sk)+'</span></div><div><strong>'+score+'</strong><small>'+date+' · level '+(a.band||1)+'</small></div></div>';}).join(''):'<p class="muted">Completed activities will appear here with the actual result and learning goal.</p>';
  var sessionRows=ins.sessions.length?ins.sessions.map(function(x){var names=x.skill_ids.slice(0,3).map(skillTitle).join(', '),result=x.accuracy===null?'guided practice':x.accuracy+'% accurate · '+x.independence+'% independent';return'<div class="history-row"><div><b>'+new Date(x.at).toLocaleDateString()+' · '+x.activities+' activities</b><span>'+names+'</span><span>'+x.suggestion+'</span></div><div><strong>'+result+'</strong><small>'+x.hints+' hints · '+x.mastery_changes+' evidence change'+(x.mastery_changes===1?'':'s')+'</small></div></div>';}).join(''):'<p class="muted">Session recommendations will appear after the first completed activity.</p>';
  var recommendationRows=ins.domains.map(function(d){var r=d.recommendation;return'<div class="history-row"><div><b>'+d.title+'</b><span>'+r.reason+'</span></div><div><strong>'+r.title+'</strong><small>'+r.action+'</small></div></div>';}).join('');
  var totalSkills=ins.domains.reduce(function(n,d){return n+d.total;},0),assessed=totalSkills-ins.unassessed;
  body.innerHTML='<div class="parent-grid">'+parentMetric('This week',ins.week.sessions+' sessions',ins.week.minutes+' minutes · '+ins.week.activities+' activities')+parentMetric('Accuracy',ins.week.accuracy===null?'—':ins.week.accuracy+'%',ins.week.independence===null?'No objective answers yet':ins.week.independence+'% independent')+parentMetric('Secure / likely knows',ins.mastered+' / '+ins.likelyKnows,'Repeated evidence / promising early evidence')+parentMetric('Developing / support',ins.developing+' / '+ins.needsSupport,'Skills still forming / needing smaller steps')+parentMetric('Evidence coverage',assessed+' of '+totalSkills,ins.unassessed+' skills honestly marked not checked yet')+parentMetric('Review queue',ins.reviewDue,ins.reviewDue?'Spaced review is due':'No spaced review due today')+parentMetric('Current challenge','Level '+Math.max(1,Math.round((ins.domains.reduce(function(n,d){return n+d.band;},0)/Math.max(1,ins.domains.length))*10)/10),'Automatically rises after fast independent success')+parentMetric('Progress safety',cloud.status==='CONNECTED'?'Synced':'On this device',cloud.status==='CONNECTED'?(cloud.email||'Parent account'):'Sign in for cross-device restore')+'</div>'+
  '<section class="parent-card parent-section today-focus"><small>TODAY’S GOAL</small><h2>'+skillTitle(nowPick&&nowPick.skill_id)+'</h2><p>'+((nowPick&&Adaptive.explain(nowPick))||'A balanced confidence-building session.')+'</p><div class="journey"><span><b>PAST</b>Foundations practiced</span><span class="current"><b>CURRENT</b>'+skillTitle(nowPick&&nowPick.skill_id)+'</span><span><b>NEXT</b>'+skillTitle(nextPick&&nextPick.skill_id)+'</span><span><b>LATER</b>Transfer to stories and real-world problems</span></div></section>'+
  '<section class="parent-card parent-section evidence-key"><h2>What Sakhi knows—and what it does not know yet</h2><p><b>Secure</b> means strong evidence over repeated work. <b>Likely knows</b> means an early independent success that unlocks a stretch task but remains scheduled for review. <b>Developing</b> means mixed evidence. <b>Needs support</b> means the last evidence calls for smaller steps. Unattempted skills stay <b>not checked yet</b>; the app does not invent mastery.</p></section>'+
  '<div class="parent-two"><section class="parent-card parent-section"><h2>Evidence by skill</h2><h3>Strongest current evidence</h3><p class="evidence-lines">'+strengths+'</p><h3>Best support targets</h3><p class="evidence-lines">'+needs+'</p></section><section class="parent-card parent-section"><h2>Last 7 days by subject</h2>'+ins.domains.map(function(d){return '<div class="parent-progress"><p><b>'+d.title+'</b><span>'+(d.accuracy===null?'No activity yet':d.accuracy+'% accuracy · '+d.independence+'% independent · level '+d.band)+'</span></p><div class="meter"><i style="width:'+d.progress+'%"></i></div><small>'+d.secure+' secure/likely · '+d.developing+' developing · '+d.support+' support · '+d.total+' skills total</small></div>';}).join('')+'</section></div>'+
  '<div class="parent-two"><section class="parent-card parent-section"><h2>Recommended next step by subject</h2>'+recommendationRows+'</section><section class="parent-card parent-section"><h2>Session-by-session guidance</h2>'+sessionRows+'</section></div>'+
  '<div class="parent-two"><section class="parent-card parent-section"><h2>Exact resume point</h2>'+resume+'</section><section class="parent-card parent-section"><h2>Recent activity history</h2>'+recentRows+'</section></div>'+
  parentCurriculumPicker()+
  '<section class="parent-card parent-section"><h2>Family account & history</h2>'+(cloud.configured?(cloud.status==='CONNECTED'?'<p class="sync-good">✓ Signed in as <b>'+cloud.email+'</b>. Progress restores on another device after sign-in.</p><div class="parent-form"><button class="soft" id="cloudSync">Sync now</button><button class="soft" id="cloudSignOut">Sign out</button></div>':'<p>Progress is always preserved on this device. Create or sign in to a free parent account for cross-device backup and restore.</p><div class="parent-form"><input class="parent-input" id="cloudEmail" type="email" autocomplete="email" placeholder="Parent email"><input class="parent-input" id="cloudPassword" type="password" autocomplete="current-password" minlength="6" placeholder="Password (6+ characters)"><button class="soft" id="cloudSignIn">Sign in</button><button class="soft" id="cloudSignUp">Create account</button></div>'):'<p class="muted">Account sync is not configured in this build; local history still remains on this device.</p>')+'</section>'+
  '<section class="parent-card parent-section"><h2>Audio readiness</h2><p class="audio-badge good">Kokoro af_heart · bundled on this device · no page wait</p><p class="muted">The learning prompt or listening passage is spoken once. Sakhi does not announce “choice 1, choice 2, choice 3,” and word-building never reads the letter bank. Hear Again repeats the same concise prompt from the local voice pack.</p><div class="audio-tools"><button class="soft" id="testVoiceBtn">🔊 Test Sakhi voice</button><span class="muted" id="audioStatusText"></span></div></section>'+
  '<section class="parent-card parent-section"><h2>Learning settings</h2><label class="parent-setting">Learner name <input class="parent-input" id="learnerName" maxlength="30" value="'+String(s.learner.name||'Sakhi').replace(/"/g,'&quot;')+'"></label><label class="parent-setting"><input type="checkbox" id="voiceToggle" '+(Audio.isEnabled()?'checked':'')+'> Spoken instructions</label><label class="parent-setting">Challenge <select id="challengeMode"><option value="AUTO">Automatically adapt</option><option value="MORE">More challenge</option><option value="GENTLE">Gentler steps</option></select></label><label class="parent-setting">Session length <select id="sessionMinutes"><option value="20">20 min</option><option value="25">25 min</option><option value="30">30 min</option></select></label><button class="soft" id="exportBtn">Export progress backup</button></section>';
  var sm=$('#sessionMinutes');sm.value=String(s.settings.session_minutes||30);sm.onchange=function(){Prog.setSetting('session_minutes',Number(sm.value));toast('Session length saved');};
  var domainSelect=$('#curriculumDomain'),skillSelect=$('#curriculumSkill');function filterCurriculum(){var domain=domainSelect.value,first=null;Array.from(skillSelect.options).forEach(function(o){var visible=o.dataset.domain===domain;o.hidden=!visible;if(visible&&!first)first=o;});if(first)skillSelect.value=first.value;}domainSelect.onchange=filterCurriculum;filterCurriculum();$('#startChosenLesson').onclick=function(){startParentLesson(skillSelect.value).catch(function(e){console.error(e);toast('That lesson could not start.');});};$('#advanceProgramDay').onclick=function(){advanceProgramDay().catch(function(e){console.error(e);toast('The next learning day could not start.');});};
  var cm=$('#challengeMode');cm.value=s.settings.challenge||'AUTO';cm.onchange=function(){Prog.setSetting('challenge',cm.value);toast('Challenge preference saved');};$('#learnerName').onchange=function(e){Prog.setLearnerName(e.target.value);toast('Learner name saved');};
  $('#voiceToggle').onchange=function(e){Audio.setEnabled(e.target.checked);Prog.setSetting('voice',e.target.checked);};
  if($('#testVoiceBtn'))$('#testVoiceBtn').onclick=async function(){var out=$('#audioStatusText');out.textContent='Opening the local Sakhi voice…';try{await ensureVoiceReady();out.textContent='✨ Instant Kokoro narration is ready.';await Audio.speak('Hello, little explorer. Shall we make a little magic? Take your time. I am right here with you.');}catch(e){out.textContent='This test could not play. Check the iPad volume and tap once more.';}};
  if($('#cloudSignIn'))$('#cloudSignIn').onclick=async function(){this.disabled=true;try{await Cloud.signIn($('#cloudEmail').value,$('#cloudPassword').value);var synced=true;try{await Prog.syncCloud();}catch(syncError){synced=false;console.warn('[Sakhi history sync]',syncError);}toast(synced?'History restored and synced':'Signed in. This device history is safe; cloud sync will retry.');await renderParent();renderStats();}catch(e){console.error(e);toast(e.message||'Could not sign in.');this.disabled=false;}};
  if($('#cloudSignUp'))$('#cloudSignUp').onclick=async function(){this.disabled=true;try{var r=await Cloud.signUp($('#cloudEmail').value,$('#cloudPassword').value);if(r.needsConfirmation){toast('Check your email to confirm the account');this.disabled=false;}else{var synced=true;try{await Prog.syncCloud();}catch(syncError){synced=false;console.warn('[Sakhi history sync]',syncError);}toast(synced?'Account created and progress synced':'Account created. This device history is safe; cloud sync will retry.');await renderParent();}}catch(e){console.error(e);toast(e.message||'Could not create account.');this.disabled=false;}};
  if($('#cloudSync'))$('#cloudSync').onclick=async function(){try{await Prog.syncCloud();toast('History is up to date');renderParent();renderStats();}catch(e){toast('Sync paused. Your device copy is safe.');}};
  if($('#cloudSignOut'))$('#cloudSignOut').onclick=async function(){await Cloud.signOut();toast('Family progress disconnected');renderParent();};
  $('#exportBtn').onclick=function(){var blob=new Blob([JSON.stringify(Prog.snapshot(),null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='sakhi-progress-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(u);};
}
async function start(){
  $('#startBtn').disabled=true;
  try{Audio.unlock().catch(function(){});if(session&&plan){if(missionIndex>plan.missions.length){Prog.endSession(session.session_id);session=null;clearRun();show('rewards');}else if(current){var resumeAdvance=awaitingNext;show('activity');if(resumeAdvance){awaitingNext=false;nextQuestion();}else beginMissionAudio();}else await loadMission();return;}plan=Plan.build();preparedMissions={};session=Prog.startSession(plan);missionIndex=0;saveRun();await loadMission();}
  catch(e){console.error('[Sakhi start]',e);toast('The adventure could not open. Tap once more to try again.');}
  finally{$('#startBtn').disabled=false;}
}
async function loadMission(){
  if(missionIndex>=plan.missions.length)return offscreenMission();
  var m=resolveMission(missionIndex);if(!m||!m.pick){plan.missions.splice(missionIndex,1);return loadMission();}var prepared=preparedMissions[missionIndex];current=prepared||Act.generate(m.pick.skill_id,m.pick.band,missionSeed(m,missionIndex),Prog.recentQuestionKeys?Prog.recentQuestionKeys(m.pick.skill_id):[]);current.activity_id=m.pick.skill_id+':'+m.pick.band+':'+session.session_id+':'+missionIndex;current._mission=m;qIndex=0;answers=[];hintLevel=0;questionTries=0;nextQuestionReady=Promise.resolve();saveRun();show('activity');beginMissionAudio();
}
function offscreenMission(){
  var domain=plan.offscreen.domain,wrap=wrapUpFor(domain);current={activity_id:'wrapup:'+domain+':'+session.session_id,skill_id:null,skill_title:'Trail finish',domain_id:domain,band:0,band_name:'WRAP-UP',evidence_mode:'practice',is_wrap_up:true,questions:[{template:'guided',prompt:wrap.prompt,narration:wrap.prompt,spoken_instruction:wrap.prompt,steps:wrap.steps,success_criteria:wrap.success,answer:'done',evidence_mode:'practice',hints:['Complete one step at a time. Ask for help only if you need it.']}]};
  current._mission={domain:domain,minutes:plan.offscreen.minutes,pick:{skill_id:null,reason:'clear learning wrap-up'}};qIndex=0;answers=[];hintLevel=0;questionTries=0;nextQuestionReady=Audio.prefetchActivity(current).catch(function(){return false;});saveRun();show('activity');beginMissionAudio();return Promise.resolve();
}
function q(){return current.questions[qIndex];}
async function speak(repeatMode){var run=++narrationRun,pill=$('#voicePill'),button=$('#hearBtn');if(pill)pill.textContent='✨ Sakhi voice';if(button)button.setAttribute('aria-busy','true');try{await Audio.narrate(q(),{repeat:!!repeatMode});}catch(e){if(run===narrationRun&&e.kind!=='DISABLED'){console.warn('[Sakhi voice]',e);if(pill)pill.textContent='📖 Read prompt';if(repeatMode)toast('This prompt is ready to read on screen.');}}finally{if(run===narrationRun&&button)button.removeAttribute('aria-busy');}}
function renderActivity(){
  if(!current)return;var d=current.domain_id,p=Prog.domainProgress(d),t=Trails.get(d),cue=Pres.storyCue(d,current.skill_title,qIndex);setWorld(d);
  clearAdvance();answerLocked=false;activityCompleted=false;$('#activityTrail').textContent=t.name;$('#activitySkill').textContent=current.skill_title;$('#activityProgress').textContent=current.is_wrap_up?'Finish line':('Quest '+(missionIndex+1)+' of '+plan.missions.length+' · Question '+(qIndex+1)+' of '+current.questions.length);$('#activityScene').innerHTML=Pres.scene(d,p,{kind:'activity',skill:current.skill_title,template:q().template,question:qIndex});$('#missionEyebrow').textContent=t.companion;$('#missionStory').textContent=cue.text||'Take your time. I’m right here.';$('#missionStep').textContent=cue.step;$('#questLabel').textContent=current.is_wrap_up?'Your clear wrap-up':current.evidence_mode==='practice'?'Guided practice · step '+(qIndex+1):'Discover · step '+(qIndex+1);$('#questionPrompt').textContent=q().prompt;$('#hintArea').textContent=hintLevel?(q().hints||[]).slice(0,hintLevel).map(function(h){return'💡 '+h;}).join('  '):'';$('#checkBtn').textContent=current.is_wrap_up?'Finish trail ✓':'Check ✓';awaitingNext=false;
  questionStartedAt=Date.now();controller=Tpl.render($('#interaction'),q(),{domain:d,onProgress:function(){if(controller)$('#checkBtn').disabled=!controller.isReady();}});$('#checkBtn').disabled=!controller.isReady();$('#hintBtn').disabled=!(q().hints||[]).length;
}
function hint(){var h=q().hints||[];if(hintLevel<h.length){hintLevel++;saveRun();$('#hintArea').textContent=h.slice(0,hintLevel).map(function(x){return'💡 '+x;}).join('  ');Audio.speak(h[hintLevel-1]).catch(function(){});}if(hintLevel>=h.length)$('#hintBtn').disabled=true;}
function check(){
  if(awaitingNext){clearAdvance();awaitingNext=false;Promise.resolve(nextQuestionReady).catch(function(){return false;}).then(nextQuestion);return;}
  if(answerLocked||!controller)return;var r=controller.check();if(!r)return;questionTries++;
  if(!r.correct&&current.evidence_mode!=='practice'&&questionTries<2){toast('Good try — here is a clue.');if(hintLevel<(q().hints||[]).length)hint();setTimeout(function(){controller.reset();$('#checkBtn').disabled=true;},500);return;}
  var responseMs=Math.max(0,Date.now()-questionStartedAt),answer={correct:r.correct,hintsUsed:hintLevel,response:r.response,tries:questionTries,response_ms:responseMs,question_key:q().question_key,difficulty:q().difficulty||current.band};answers.push(answer);
  if(Prog.recordQuestion)Prog.recordQuestion({session_id:session&&session.session_id,activity_id:current.activity_id,skill_id:current.skill_id,domain_id:current.domain_id,question_index:qIndex,question_key:q().question_key,correct:r.correct,hints:hintLevel,tries:questionTries,response_ms:responseMs,difficulty:q().difficulty||current.band});
  var strongPair=current.evidence_mode!=='practice'&&answers.length>=2&&answers.slice(-2).every(function(x){return x.correct&&!x.hintsUsed&&x.tries===1&&x.response_ms<=10000;})&&qIndex<current.questions.length-1;if(strongPair){current.fast_track_complete=true;nextQuestionReady=Promise.resolve(true);}else if(qIndex<current.questions.length-1&&current.evidence_mode!=='practice')nextQuestionReady=adaptNextQuestion(r.correct&&hintLevel===0&&questionTries===1&&responseMs<=10000,r.correct);else nextQuestionReady=Promise.resolve(true);
  $('#hintArea').textContent=strongPair?'You showed this skill twice on your own. A new challenge is next!':r.correct?'You found it! The next example is ready.':'We’ll practice that idea with a new example.';$('#hintBtn').disabled=true;$('#checkBtn').disabled=false;$('#checkBtn').textContent=strongPair?'New challenge →':current.is_wrap_up?'See my trail finish →':'Next discovery →';awaitingNext=true;answerLocked=true;saveRun();advanceTimer=setTimeout(function(){advanceTimer=null;if(awaitingNext){awaitingNext=false;Promise.resolve(nextQuestionReady).catch(function(){return false;}).then(nextQuestion);}},850);
}
function adaptNextQuestion(fastIndependent,correct){
  var currentDifficulty=Number(q().difficulty||current.band)||1,target=fastIndependent?Math.min(5,currentDifficulty+1):correct?currentDifficulty:Math.max(1,currentDifficulty-1),avoid=(Prog.recentQuestionKeys?Prog.recentQuestionKeys(current.skill_id):[]).concat(current.questions.map(function(x){return x.question_key;})),seed=[session&&session.session_id,current.activity_id,'adaptive',qIndex,answers.length,target].join(':');
  try{var generated=Act.generate(current.skill_id,target,seed,avoid),replacement=generated.questions.find(function(x){return avoid.indexOf(x.question_key)<0;})||generated.questions[0];if(replacement){current.questions[qIndex+1]=replacement;return Audio.prefetch(replacement).catch(function(){return false;});}}catch(e){console.warn('[Sakhi adaptive question]',e&&e.message||e);}return Promise.resolve(false);
}
function nextQuestion(){clearAdvance();if(current.fast_track_complete){delete current.fast_track_complete;return finishActivity();}if(qIndex<current.questions.length-1){qIndex++;hintLevel=0;questionTries=0;awaitingNext=false;nextQuestionReady=Promise.resolve();saveRun();renderActivity();speak(false);}else finishActivity();}
function finishActivity(){
  clearAdvance();if(activityCompleted)return;activityCompleted=true;
  var result=current.is_wrap_up?Prog.completeWrapUp({activity:current,sessionId:session.session_id,answers:answers}):Prog.completeActivity({activity:current,sessionId:session.session_id,answers:answers});if(!current.is_wrap_up)prepareMission(missionIndex+1,true).catch(function(){});saveRun(missionIndex+1,null);renderStats();var t=Trails.get(current.domain_id),amount=result.rewards_issued.length?result.rewards_issued[0].amount:0,finalMission=!!current.is_wrap_up,learned=plan.missions.map(function(m){var sk=m.pick&&Cur.skill(m.pick.skill_id);return sk&&sk.title;}).filter(Boolean);$('#celebrateIcon').innerHTML='<img src="'+(window.SAKHI_ICON_DATA||'./icon-192.png')+'" alt="">';$('#celebrateTitle').textContent=finalMission?'Trail complete!':current.skill_title+' complete!';$('#celebrateBody').textContent=finalMission?('You explored '+learned.join(', ')+'. Your finish-line example connected the learning.'):result.accuracy===1&&result.independent===answers.length?('You solved '+answers.length+' on your own. The next quest moves to a new idea or harder challenge.'):(t.companion+' saved what you know and prepared a different example next.');$('#celebrateReward').textContent='✦ '+amount+' trail stars earned';$('#continueBtn').textContent=finalMission?'See my treasures →':'Next learning quest →';$('#celebrate').classList.add('show');
  var rewardMedia=Pres.mediaFor&&Pres.mediaFor(current.domain_id,current.skill_title,q().template,qIndex);if(rewardMedia)$('#celebrateIcon').innerHTML='<img src="'+rewardMedia.src+'" alt="'+rewardMedia.alt+'">';
}
async function continueAfter(){
  var button=$('#continueBtn'),overlay=$('#celebrate');if(transitioning||!overlay.classList.contains('show'))return;transitioning=true;var previousIndex=missionIndex;
  button.disabled=true;button.setAttribute('aria-busy','true');Audio.stopAll();narrationRun++;overlay.classList.remove('show');
  try{
    missionIndex=previousIndex+1;
    if(missionIndex>plan.missions.length){if(session)Prog.endSession(session.session_id);session=null;current=null;clearRun();show('rewards');}
    else{await loadMission();if(missionIndex===previousIndex)throw new Error('Adventure did not advance');window.scrollTo(0,0);}
  }catch(e){console.error('[Sakhi next adventure]',e);missionIndex=previousIndex;saveRun();overlay.classList.add('show');toast('That adventure paused. Tap once more to continue.');}
  finally{transitioning=false;button.disabled=false;button.removeAttribute('aria-busy');}
}
function bind(){
  document.querySelectorAll('[data-nav]').forEach(function(b){b.onclick=function(){if(current&&session)saveRun();show(b.dataset.nav);};});document.addEventListener('click',function(e){var card=e.target.closest&&e.target.closest('[data-trail-domain]');if(card)startTrail(card.dataset.trailDomain);});document.addEventListener('keydown',function(e){var card=e.target.closest&&e.target.closest('[data-trail-domain]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();startTrail(card.dataset.trailDomain);}});$('#startBtn').onclick=start;$('#modeUnicorn').onclick=function(){setAdventureMode('unicorn');};$('#modePrincess').onclick=function(){setAdventureMode('princess');};$('#quitBtn').onclick=function(){saveRun();Audio.stopAll();show('home');toast('Saved exactly here for next time.');};$('#hearBtn').onclick=async function(){try{await ensureVoiceReady();await speak(true);}catch(e){console.warn('[Sakhi repeat]',e);toast('This prompt is ready to read on screen.');}};$('#hintBtn').onclick=hint;$('#checkBtn').onclick=check;$('#continueBtn').onclick=continueAfter;$('#gateBtn').onclick=function(){var answer=String($('#gateAnswer').value||'').replace(/\s/g,'');if(answer==='071621'){parentOpen=true;$('#gateAnswer').value='';renderParent();}else toast('Try the grown-up question again. That passcode did not match.');};Audio.onFault(function(e){console.warn('[Sakhi audio]',e.kind,e.message);});
}
function bootFailure(e){
  console.error('[Sakhi boot failed]',e);window.__SAKHI_BOOT_ERROR=String(e&&e.message||e);var box=$('#bootFallback');if(box){box.hidden=false;var detail=box.querySelector('[data-boot-detail]');if(detail)detail.textContent='Build '+(window.SAKHI_BUILD_ID||'unknown')+' · '+window.__SAKHI_BOOT_ERROR;}
}
async function boot(){
  loadRun();
  try{await Cur.load();Prog.load();Audio.setEnabled(Prog.load().settings.voice!==false);bind();var authResult=Cloud&&Cloud.consumeAuthCallback?Cloud.consumeAuthCallback():null;if(Cloud&&Cloud.probe){await Cloud.probe().catch(function(e){console.warn('Cloud probe',e.message);});if(Cloud.state().status==='CONNECTED'){await Prog.syncCloud().catch(function(e){console.warn('History sync',e.message);});loadRun();}}renderHome();renderStats();if(authResult&&authResult.status==='confirmed')toast('Parent email confirmed. You are signed in and learning history is synced.');else if(authResult&&authResult.status==='error')toast(authResult.message);if(Audio.isEnabled()&&Audio.warm)Audio.warm().catch(function(e){console.warn('[Sakhi] Voice warm-up',e&&e.message||e);});window.__SAKHI_BOOTED=true;document.documentElement.classList.add('sakhi-ready');if('serviceWorker'in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('./sw.js?v=4.4.2',{updateViaCache:'none'}).then(function(r){r.update().catch(function(){});}).catch(function(e){console.warn('SW',e.message);});}}
  catch(e){bootFailure(e);}
}
window.SakhiApp={boot:boot,show:show};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
