window.SakhiContent=(function(){
'use strict';
var LETTERS='abcdefghijklmnopqrstuvwxyz'.split('');
var UPPER=LETTERS.map(function(x){return x.toUpperCase();});
var CVC=['cat','map','sun','pig','dog','hen','jet','lip','rug','top','bed','fan','sit','mop','run','cap','pin','fox','mud','van'];
var DIGRAPHS={sh:['ship','fish','shop','shell'],ch:['chip','chop','chin','lunch'],th:['thin','moth','bath','this'],wh:['when','whip','whale','wheel'],ck:['duck','sock','rock','back'],ng:['ring','song','king','wing']};
var BLENDS={st:['star','stop','step'],bl:['black','blue','block'],cl:['clap','clip','clock'],gr:['green','grab','grin'],tr:['tree','trip','truck'],pl:['plan','plum','plug']};
var SIGHT=['the','is','a','I','to','you','we','my','was','said','are','of'];
var SENTENCES=['The cat sat on the mat.','I can see a red sun.','The pig is in the mud.','We run to the big hill.','My dog can hop.','A fish can swim fast.','The shell is on the sand.','I like the green tree.'];
var STORIES=[
 {text:'Mia has a red hat. The wind lifts it up. A kind bird sees the hat and drops it near Mia. Mia smiles and says thank you.',q:'Who helped Mia?',a:'the bird',options:['the bird','a fish','a frog']},
 {text:'Lina plants a seed in a pot. She gives it water and puts it by a sunny window. A tiny green sprout appears.',q:'What helped the seed grow?',a:'water and sun',options:['water and sun','candy','snow']},
 {text:'A little crab finds a shiny shell. It is too big for the crab. The crab leaves it beside a rock for another animal.',q:'What did the crab find?',a:'a shell',options:['a shell','a crown','a kite']},
 {text:'Nora builds a tower with four blocks. Her kitten bumps it and the tower falls. Nora takes a breath and builds it again.',q:'What did Nora do after the tower fell?',a:'built it again',options:['built it again','went to sleep','ate it']}
,{text:'Leo found a lost kitten by the gate. He gave it water and told his mum. Together they found the kitten’s owner next door.',q:'What did Leo do first?',a:'he gave the kitten water',options:['he gave the kitten water','he kept the kitten','he walked away']},{text:'Priya planted three seeds in a pot. She watered them every morning. After two weeks a small green shoot appeared.',q:'How long until the shoot appeared?',a:'about two weeks',options:['about two weeks','one day','a whole year']},{text:'The class went to the park. It began to rain, so they ate lunch under the big shelter. Everyone stayed dry.',q:'Why did the class eat under the shelter?',a:'because it was raining',options:['because it was raining','because they were cold','because the park closed']},{text:'Sam built a tower of blocks. It wobbled and fell. He made the bottom wider and tried again, and this time it stood tall.',q:'What did Sam change?',a:'he made the bottom wider',options:['he made the bottom wider','he used fewer blocks','he gave up']},{text:'Grandma showed Nia an old photograph. In it, Grandma was a little girl holding a wooden toy. Nia laughed because Grandma looked just like her.',q:'Who was the little girl in the photo?',a:'Grandma',options:['Grandma','Nia','Nia’s mum']},{text:'A squirrel buried nuts under the oak tree before winter. When the snow came, it dug them up to eat.',q:'Why did the squirrel bury the nuts?',a:'to save food for winter',options:['to save food for winter','to plant a tree','to hide from the snow']},{text:'Theo forgot his lunchbox. His friend Ama shared half her sandwich with him. Theo said he would bring her a treat tomorrow.',q:'How did Ama help Theo?',a:'she shared her sandwich',options:['she shared her sandwich','she bought him lunch','she went home']},{text:'The lighthouse shone all night. A small boat followed its light safely past the rocks and into the harbour.',q:'What did the lighthouse help the boat do?',a:'avoid the rocks',options:['avoid the rocks','go faster','catch fish']}];
var SEQUENCES=[
 {text:'Ava mixed flour and water. She shaped the dough. Then she baked it with a grown-up.',a:'She baked the dough.',options:['She baked the dough.','She planted the dough.','She put on boots.']},
 {text:'Leo found library books on the floor. He stacked them, carried them to the shelf, and put them away.',a:'He put the books on the shelf.',options:['He put the books on the shelf.','He threw the books.','He painted the shelf.']},
 {text:'Nia dug a small hole, placed a seed inside, and covered it with soil.',a:'The seed was covered with soil.',options:['The seed was covered with soil.','The seed flew away.','The soil became ice.']}
,{text:'Rosa poured the paint. She dipped her brush. Then she painted a bright blue sky.',a:'She painted the sky.',options:['She painted the sky.','She poured the paint.','She washed the brush first.']},{text:'Dev packed his bag. He put on his coat. Then he walked to the bus stop.',a:'He walked to the bus stop.',options:['He walked to the bus stop.','He packed his bag.','He took off his coat.']},{text:'The caterpillar ate leaves. It made a chrysalis. Then it came out as a butterfly.',a:'It came out as a butterfly.',options:['It came out as a butterfly.','It ate more leaves.','It became an egg again.']},{text:'Mira filled the tub. She added bubbles. Then she washed the muddy dog.',a:'She washed the dog.',options:['She washed the dog.','She filled the tub.','She dried the dog first.']},{text:'The seed was planted. A shoot pushed up through the soil. Then leaves opened in the sunlight.',a:'Leaves opened in the sunlight.',options:['Leaves opened in the sunlight.','The seed was planted.','The shoot went back down.']},{text:'Jay chose a book. He sat on the beanbag. Then he read until the bell rang.',a:'He read until the bell rang.',options:['He read until the bell rang.','He chose a book.','He put the book away first.']},{text:'The baker mixed the dough. He left it to rise. Then he baked it into warm bread.',a:'He baked it into bread.',options:['He baked it into bread.','He mixed the dough.','He ate the flour.']},{text:'Ella tied her laces. She stretched her legs. Then she ran the race.',a:'She ran the race.',options:['She ran the race.','She tied her laces.','She took off her shoes.']}];
var PREDICTIONS=[
 {text:'Dark clouds fill the sky. Sam opens an umbrella.',a:'Rain may begin.',options:['Rain may begin.','The sun will get brighter.','The umbrella will become a boat.']},
 {text:'The puppy waits beside its empty bowl and wags when Mia picks up the food bag.',a:'Mia will feed the puppy.',options:['Mia will feed the puppy.','The puppy will read.','Mia will hide the bowl.']},
 {text:'Zara adds one block to a very wobbly tower.',a:'The tower may fall.',options:['The tower may fall.','The tower may become steadier.','The new block may slide off.']}
,{text:'Noor fills a watering can and walks towards the dry seedlings.',a:'She will water the plants.',options:['She will water the plants.','She will paint the pot.','The plants will fly away.']},{text:'The cat crouches low and stares at a fluttering leaf.',a:'The cat will pounce.',options:['The cat will pounce.','The cat will fall asleep.','The leaf will chase the cat.']},{text:'Ben stacks one more block on a tower that is already leaning.',a:'The tower will probably fall.',options:['The tower will probably fall.','The tower will straighten itself.','The blocks will vanish.']},{text:'Dark clouds gather and the class is lining up to go outside.',a:'They may stay indoors.',options:['They may stay indoors.','The sun will come out instantly.','They will swim.']},{text:'Lina blows out all the candles on her cake while everyone claps.',a:'They will eat the cake.',options:['They will eat the cake.','They will light the candles again.','They will go to bed.']},{text:'The ice cream has been left on a sunny windowsill.',a:'It will melt.',options:['It will melt.','It will freeze harder.','It will grow bigger.']},{text:'Ravi has packed a towel, goggles and sun cream into his bag.',a:'He is going swimming.',options:['He is going swimming.','He is going to bed.','He is going skiing.']},{text:'The library bell rings and children begin putting books back on the shelves.',a:'The session is ending.',options:['The session is ending.','The session is starting.','They will read all night.']}];
var CAUSES=[
 {text:'Omar left an ice cube in the sun. Soon there was a puddle.',q:'Why was there a puddle?',a:'The ice melted in warmth.',options:['The ice melted in warmth.','The ice grew roots.','The sun froze it.']},
 {text:'The plant had not been watered for many days. Its leaves drooped.',q:'Why did the leaves droop?',a:'The plant needed water.',options:['The plant needed water.','The plant was dancing.','The pot was too blue.']},
 {text:'Priya wore boots because the playground had deep puddles.',q:'Why did Priya wear boots?',a:'to keep her feet dry',options:['to keep her feet dry','to make the puddles bigger','to help her fly']}
,{text:'Nina left her bicycle out in the rain all week. Now the chain is orange and rough.',q:'Why is the chain rough?',a:'it rusted in the rain',options:['it rusted in the rain','someone painted it','it grew fur']},{text:'The plant on the dark shelf grew pale and droopy, while the one by the window stayed green.',q:'Why did one plant droop?',a:'it did not get enough light',options:['it did not get enough light','it had too many leaves','it was too green']},{text:'Tom ran all the way home. When he arrived he was breathing hard.',q:'Why was Tom breathing hard?',a:'because he had been running',options:['because he had been running','because it was cold','because he was reading']},{text:'The snowman stood in the garden. By the afternoon the sun was strong and only a hat and a scarf were left.',q:'Why did the snowman disappear?',a:'the sun melted it',options:['the sun melted it','someone carried it away','it walked off']},{text:'Maya forgot to put the lid on the paint pot. The next morning the paint was dry and cracked.',q:'Why did the paint dry out?',a:'the lid was left off',options:['the lid was left off','the paint was old','it was stirred too much']},{text:'The seedlings by the window all leaned towards the glass.',q:'Why did they lean?',a:'they grew towards the light',options:['they grew towards the light','the pot was tilted','the wind pushed them']},{text:'Ali wore thin shoes in the puddles. Soon his socks were soaking.',q:'Why were his socks wet?',a:'water came through his shoes',options:['water came through his shoes','he spilled his drink','it was snowing']}];
var INFERENCES=[
 {text:'Kai comes inside shaking drops from his coat. He closes his umbrella.',q:'What is the weather probably like?',a:'rainy',options:['rainy','dry and sunny','cold but dry']},
 {text:'Lulu yawns, rubs her eyes, and curls under a blanket.',q:'How does Lulu probably feel?',a:'tired',options:['tired','hungry for soup','ready to race']},
 {text:'Noah carries a wrapped box and a card into the party room.',q:'What is probably inside the box?',a:'a gift',options:['a gift','party plates','a folded jacket']}
,{text:'Sara tiptoes into the room carrying a wrapped box and a card, and everyone whispers.',q:'What is probably happening?',a:'a surprise party',options:['a surprise party','a spelling test','bedtime']},{text:'The kitchen smells of warm bread and there is flour on the table and on Dad’s nose.',q:'What has Dad probably been doing?',a:'baking',options:['baking','gardening','painting']},{text:'Ira zips her coat to the chin, pulls on gloves and breathes out a cloud of white.',q:'What is the weather probably like?',a:'very cold',options:['very cold','hot and sunny','warm and still']},{text:'The classroom floor is covered in paper scraps, glue sticks and glitter, and everyone is smiling.',q:'What have they probably been doing?',a:'making crafts',options:['making crafts','taking a nap','running a race']},{text:'Max keeps checking the clock and his packed bag is by the door.',q:'What is Max probably doing?',a:'waiting to leave',options:['waiting to leave','starting homework','unpacking']},{text:'The puppy’s bowl is empty, it is nudging Ben’s leg and whining softly.',q:'What does the puppy probably want?',a:'food',options:['food','a bath','to sleep']},{text:'Everyone is clapping, a girl is holding a trophy, and confetti is falling.',q:'What probably just happened?',a:'she won something',options:['she won something','she lost her bag','the lesson began']}];
var MAIN_IDEAS=[
 {text:'Bees visit flowers and carry pollen. This helps many plants make seeds and fruit.',a:'Bees help plants grow.',options:['Bees help plants grow.','Bees collect food only for birds.','Flowers grow without pollination.']},
 {text:'At the library, people can borrow books, hear stories, and learn about many topics.',a:'Libraries are places to read and learn.',options:['Libraries are places to read and learn.','Libraries are only quiet meeting rooms.','All library books tell the same story.']},
 {text:'A class planted seeds, measured the sprouts, and wrote down what changed each day.',a:'The class observed how plants grow.',options:['The class observed how plants grow.','The class compared different playground games.','The class practiced sorting finished books.']}
,{text:'Elephants use their trunks to drink, to pick up food and to spray water over their backs to stay cool.',a:'Elephants use their trunks in many ways.',options:['Elephants use their trunks in many ways.','Elephants like water.','Elephants are grey.']},{text:'Wash your hands before eating, after playing outside and after using the toilet. Clean hands help stop germs spreading.',a:'Washing hands helps keep us healthy.',options:['Washing hands helps keep us healthy.','Soap smells nice.','Germs are tiny.']},{text:'Some birds fly thousands of miles each autumn to reach warmer places, then return in spring when food is plentiful again.',a:'Some birds migrate to find warmth and food.',options:['Some birds migrate to find warmth and food.','Birds have feathers.','Spring is warm.']},{text:'Recycling paper, glass and plastic means less rubbish is buried and fewer new materials need to be made.',a:'Recycling helps reduce waste.',options:['Recycling helps reduce waste.','Glass is see-through.','Bins are often blue.']},{text:'Trees give shade on hot days, homes for birds and insects, and they help clean the air we breathe.',a:'Trees are useful in many ways.',options:['Trees are useful in many ways.','Trees are tall.','Birds like branches.']},{text:'A spider spins a web from silk, waits quietly, and catches insects that fly into the sticky threads.',a:'Spiders use webs to catch food.',options:['Spiders use webs to catch food.','Silk is strong.','Spiders have eight legs.']},{text:'Firefighters wear thick suits, carry hoses and use ladders so they can reach people safely in a fire.',a:'Firefighters use special equipment to help people.',options:['Firefighters use special equipment to help people.','Ladders are tall.','Fires are hot.']}];
var VOCAB=[
 {w:'enormous',m:'very big',o:['very big','very cold','very quiet']},
 {w:'gentle',m:'soft and kind',o:['soft and kind','loud and rough','very fast']},
 {w:'delighted',m:'very happy',o:['very happy','very tired','very wet']},
 {w:'brave',m:'ready to try even when nervous',o:['ready to try even when nervous','always sleepy','very small']},
 {w:'tiny',m:'very small',o:['very small','very loud','very bright']}
,{w:'ancient',m:'very old',o:['very old','very new','very loud']},{w:'fragile',m:'breaks easily',o:['breaks easily','very strong','very heavy']},{w:'curious',m:'wanting to find out',o:['wanting to find out','very tired','very angry']},{w:'generous',m:'happy to share',o:['happy to share','keeps everything','always late']},{w:'rapid',m:'very fast',o:['very fast','very slow','very soft']},{w:'silent',m:'making no sound',o:['making no sound','very bright','very wet']},{w:'cautious',m:'careful about danger',o:['careful about danger','in a big hurry','very funny']},{w:'content',m:'happy with what you have',o:['happy with what you have','very hungry','very noisy']}];
var SHAPES=[
 {name:'circle',src:'./assets/educational/shapes/circle.svg'},
 {name:'triangle',src:'./assets/educational/shapes/triangle.svg'},
 {name:'square',src:'./assets/educational/shapes/square.svg'},
 {name:'cube',src:'./assets/educational/shapes/cube.svg'},
 {name:'sphere',src:'./assets/educational/shapes/sphere.svg'}
];
var SCI=[
 {q:'Which animal lives in the ocean?',a:'fish',options:['fish','camel','bear']},
 {q:'What does a plant need to grow?',a:'water and light',options:['water and light','shoes and hats','candy and rocks']},
 {q:'What should we do before deciding if an object floats?',a:'make a prediction and test it',options:['make a prediction and test it','guess and stop','throw it away']},
 {q:'What can a magnet attract?',a:'some metal objects',options:['some metal objects','every object','only water']},
 {q:'What gives Earth light during the day?',a:'the sun',options:['the sun','the moon','a cloud']}
];
var LOGIC=[
 {q:'Which arrow moves right?',a:'➡️',options:['➡️','⬅️','⬆️']},
 {q:'Big, bigger, biggest. Which is the largest?',a:'biggest',options:['biggest','big','bigger']},
 {q:'All cats have whiskers. Luna is a cat. So Luna has…',a:'whiskers',options:['whiskers','wings','fins']},
 {q:'Which one does not belong: spoon, fork, shoe?',a:'shoe',options:['shoe','spoon','fork']},
 {q:'If today is Tuesday, what day comes next?',a:'Wednesday',options:['Wednesday','Monday','Sunday']},
 {q:'A circle, a square, a circle, a square. What comes next?',a:'a circle',options:['a circle','a square','a triangle']},
 {q:'You need to be dry in the rain. What helps most?',a:'an umbrella',options:['an umbrella','a fan','a spoon']},
 {q:'Which is heavier, a feather or a brick?',a:'a brick',options:['a brick','a feather','they are equal']},
 {q:'Sort these by size, smallest first: elephant, cat, ant. Which is first?',a:'ant',options:['ant','cat','elephant']},
 {q:'If all the blue blocks are gone, which colors could be left?',a:'red and yellow',options:['red and yellow','only blue','none at all']},
 {q:'Which one does not belong: apple, banana, chair?',a:'chair',options:['chair','apple','banana']},
 {q:'It is raining and the ground is dry under the tree. Why?',a:'the branches blocked the rain',options:['the branches blocked the rain','the rain went up','the tree drank it all']},
 {q:'Three friends share six apples equally. How many each?',a:'two',options:['two','three','six']}
];
var WELL=[
 {q:'A friend is sad. What is a kind choice?',a:'ask if they want help',options:['ask if they want help','laugh at them','take their toy']},
 {q:'You feel frustrated. What can help?',a:'pause and take a slow breath',options:['pause and take a slow breath','throw something','shout at everyone']},
 {q:'What should you do before crossing a street with a grown-up?',a:'stop and look both ways',options:['stop and look both ways','run quickly','close your eyes']}
];
return {LETTERS:LETTERS,UPPER:UPPER,CVC:CVC,DIGRAPHS:DIGRAPHS,BLENDS:BLENDS,SIGHT:SIGHT,SENTENCES:SENTENCES,STORIES:STORIES,SEQUENCES:SEQUENCES,PREDICTIONS:PREDICTIONS,CAUSES:CAUSES,INFERENCES:INFERENCES,MAIN_IDEAS:MAIN_IDEAS,VOCAB:VOCAB,SHAPES:SHAPES,SCI:SCI,LOGIC:LOGIC,WELL:WELL};
})();
