window.SakhiCloud=(function(){
'use strict';
var CFG=Object.assign({},window.RAINBOW_CONFIG||{},window.SAKHI_CONFIG||{});
var BASE=CFG.supabaseUrl||'',ANON=CFG.supabaseAnonKey||CFG.supabasePublishableKey||'',SPEECH_URL=CFG.speechFunctionUrl||CFG.ttsEndpoint||'';
var OUT='sakhi.v3.outbox',DEAD='sakhi.v3.deadletter',SESSION='sakhi.cloud.session',listeners=[],verified=false,flushing=false,lastError=null,snapshotTimer=null;
function queueScope(){var s=session();return s&&s.user&&s.user.id?'user-'+s.user.id:'guest';}
function outKey(){return OUT+'.'+queueScope();}
function deadKey(){return DEAD+'.'+queueScope();}
var AUTH_CALLBACK_KEYS=['access_token','refresh_token','expires_in','expires_at','token_type','type','error','error_code','error_description'];
function read(k,f){try{var v=localStorage.getItem(k);return v?JSON.parse(v):f;}catch(e){return f;}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch(e){return false;}}
function session(){return read(SESSION,null);}
function setSession(v){if(v)write(SESSION,v);else try{localStorage.removeItem(SESSION);}catch(e){}verified=false;emit();}
function configured(){return!!(BASE&&ANON);}
function callbackParams(){var query=new URLSearchParams(location.search||''),hash=new URLSearchParams(String(location.hash||'').replace(/^#/,''));return{get:function(k){return hash.get(k)||query.get(k);},query:query,hash:hash};}
function isLocalHost(){return/^(localhost|127\.0\.0\.1|0\.0\.0\.0)$/i.test(location.hostname||'');}
function authRedirect(){return(location.origin||'')+(location.pathname||'/');}
async function authFetch(url,opts,label){try{return await fetch(url,opts);}catch(e){throw new Error((label||'Supabase request')+' could not reach the parent account service from '+(location.origin||'this page')+'.');}}
function authErrorMessage(d,fallback){var code=d&&d.error_code||d&&d.code||'',msg=d&&d.msg||d&&d.error_description||d&&d.message||'';if(code==='invalid_credentials'||/invalid login credentials/i.test(msg))return'That password did not match this parent account. Use the email sign-in link if you do not remember it.';if(/email not confirmed/i.test(msg))return'Confirm the parent email first, then sign in again.';return msg||fallback;}
function clearAuthCallback(query){AUTH_CALLBACK_KEYS.forEach(function(k){query.delete(k);});var qs=query.toString(),clean=(location.pathname||'/')+(qs?'?'+qs:'');if(typeof history!=='undefined'&&history.replaceState)history.replaceState(null,'',clean);}
function consumeAuthCallback(){var p=callbackParams(),touched=AUTH_CALLBACK_KEYS.some(function(k){return p.get(k)!==null;});if(!touched)return null;var problem=p.get('error_description')||p.get('error'),code=p.get('error_code')||p.get('error'),type=p.get('type')||'';clearAuthCallback(p.query);if(problem){var expired=code==='otp_expired'||/expired|invalid|not found/i.test(problem),message=expired?'This email link was already used or expired. Request a new email sign-in link from Parents.':problem;lastError=message;emit();return{status:'error',code:code||'auth_callback_error',message:message};}var access=p.get('access_token'),refreshToken=p.get('refresh_token');if(!access||!refreshToken){lastError='The email link did not contain a complete parent session.';emit();return{status:'error',code:'incomplete_callback',message:lastError};}var expiresIn=Number(p.get('expires_in'))||3600,expiresAt=Number(p.get('expires_at'))||Math.floor(Date.now()/1000)+expiresIn;lastError=null;setSession({access_token:access,refresh_token:refreshToken,expires_in:expiresIn,expires_at:expiresAt,token_type:p.get('token_type')||'bearer'});return{status:type==='recovery'?'recovery':'confirmed',type:type};}
function status(){if(!configured())return'NOT_CONFIGURED';if(navigator.onLine===false)return'OFFLINE';var s=session();return s&&s.access_token&&verified?'CONNECTED':'NOT_CONNECTED';}
function state(){var s=session();return{status:status(),pending:read(outKey(),[]).length,dead:read(deadKey(),[]).length,configured:configured(),signedIn:!!(s&&s.access_token),email:s&&s.user&&s.user.email||null,userId:s&&s.user&&s.user.id||null,error:lastError};}
function emit(){var s=state();listeners.forEach(function(fn){try{fn(s);}catch(e){}});}
function onChange(fn){listeners.push(fn);return function(){listeners=listeners.filter(function(x){return x!==fn;});};}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16);});}
function headers(useAuth){var s=session(),token=useAuth!==false&&s&&s.access_token?s.access_token:ANON;return{'apikey':ANON,'Content-Type':'application/json','Authorization':'Bearer '+token};}
async function refresh(){var s=session();if(!s||!s.refresh_token)return false;try{var r=await fetch(BASE+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'apikey':ANON,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok)return false;setSession(await r.json());return true;}catch(e){return false;}}
async function request(path,opts){opts=opts||{};if(!configured())throw new Error('Supabase not configured');if(navigator.onLine===false)throw new Error('Offline');var r=await fetch(BASE+path,{method:opts.method||'GET',headers:Object.assign(headers(opts.auth!==false),opts.headers||{}),body:opts.body?JSON.stringify(opts.body):undefined});if((r.status===401||r.status===403)&&opts.auth!==false&&!opts._retried&&await refresh())return request(path,Object.assign({},opts,{_retried:true}));if(!r.ok)throw new Error('HTTP '+r.status+' '+await r.text());var t=await r.text();return t?JSON.parse(t):null;}
async function probe(){
  if(!configured()){verified=false;emit();return state();}
  if(navigator.onLine===false){verified=false;emit();return state();}
  var s=session();if(!s||!s.access_token){verified=false;emit();return state();}
  try{var user=await request('/auth/v1/user');if(user&&user.id){s.user=user;write(SESSION,s);}verified=true;lastError=null;emit();flush();}
  catch(e){verified=false;lastError=String(e.message||e);emit();}
  return state();
}
function enqueue(batch){var q=read(outKey(),[]);q.push({op_id:uuid(),at:new Date().toISOString(),batch:batch,tries:0});write(outKey(),q);emit();flush();}
async function flush(){if(flushing||status()!=='CONNECTED')return;flushing=true;var ok=outKey(),dk=deadKey(),q=read(ok,[]),dead=read(dk,[]);try{while(q.length){var op=q[0];try{await request('/rest/v1/sakhi_v3_events',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:op.batch});q.shift();write(ok,q);emit();}catch(e){op.tries=(op.tries||0)+1;if(/HTTP 4/.test(String(e.message))&&op.tries>=3){dead.push(Object.assign(op,{error:String(e.message)}));q.shift();write(dk,dead);write(ok,q);emit();continue;}lastError=String(e.message||e);break;}}}finally{flushing=false;}}
async function loadSnapshot(){
  var s=session(),userId=s&&s.user&&s.user.id;if(!userId||status()!=='CONNECTED')return{synced:false,reason:'not-connected',snapshot:null};
  var rows=await request('/rest/v1/sakhi_family_state?user_id=eq.'+encodeURIComponent(userId)+'&select=snapshot,updated_at&limit=1'),remote=rows&&rows[0];
  return{synced:true,snapshot:remote&&remote.snapshot||null,updated_at:remote&&remote.updated_at||null};
}
async function saveSnapshot(localSnapshot){
  var s=session(),userId=s&&s.user&&s.user.id;if(!userId||status()!=='CONNECTED')return{synced:false,reason:'not-connected'};
  var stamp=new Date().toISOString(),snap=Object.assign({},localSnapshot||{},{updated_at:stamp});
  await request('/rest/v1/sakhi_family_state?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{user_id:userId,snapshot:snap,updated_at:stamp}});
  return{synced:true,direction:'upload',snapshot:snap};
}
async function syncSnapshot(localSnapshot){var remote=await loadSnapshot();if(!remote.synced)return remote;if(remote.snapshot)return{synced:true,direction:'download',snapshot:remote.snapshot};return saveSnapshot(localSnapshot);}
function scheduleSnapshot(snapshot){clearTimeout(snapshotTimer);if(status()!=='CONNECTED')return;snapshotTimer=setTimeout(function(){saveSnapshot(snapshot).catch(function(e){lastError=String(e.message||e);emit();});},650);}
function credentials(email,password){email=String(email||'').trim().toLowerCase();password=String(password||'');if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('Enter a valid parent email address.');if(password.length<6)throw new Error('Password must contain at least 6 characters.');return{email:email,password:password};}
async function signIn(email,password){if(!configured())throw new Error('Supabase not configured');var input=credentials(email,password),r=await authFetch(BASE+'/auth/v1/token?grant_type=password',{method:'POST',headers:{'apikey':ANON,'Content-Type':'application/json'},body:JSON.stringify(input)},'Sign in');if(!r.ok){var d=null;try{d=await r.json();}catch(e){}throw new Error(authErrorMessage(d,'Email or password did not match.'));}setSession(await r.json());await probe();if(status()!=='CONNECTED')throw new Error('Signed in, but Sakhi could not verify the parent account.');return state();}
async function sendMagicLink(email){if(!configured())throw new Error('Supabase not configured');email=String(email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('Enter a valid parent email address.');var target=isLocalHost()?'https://sakhilearning.github.io/':authRedirect(),r=await authFetch(BASE+'/auth/v1/otp?redirect_to='+encodeURIComponent(target),{method:'POST',headers:{'apikey':ANON,'Content-Type':'application/json'},body:JSON.stringify({email:email,create_user:false})},'Email sign-in');if(!r.ok){var d=null;try{d=await r.json();}catch(e){}throw new Error(authErrorMessage(d,'Could not send the sign-in email.'));}return{sent:true,redirect:target};}
async function signUp(email,password){if(!configured())throw new Error('Supabase not configured');var input=credentials(email,password),suffix=isLocalHost()?'':'?redirect_to='+encodeURIComponent(authRedirect()),r=await authFetch(BASE+'/auth/v1/signup'+suffix,{method:'POST',headers:{'apikey':ANON,'Content-Type':'application/json'},body:JSON.stringify(input)},'Create account');if(!r.ok){var d=null;try{d=await r.json();}catch(e){}throw new Error(authErrorMessage(d,'Account could not be created.'));}var v=await r.json();if(v.access_token){setSession(v);await probe();}return{needsConfirmation:!v.access_token,local:isLocalHost()};}
async function resendConfirmation(email){if(!configured())throw new Error('Supabase not configured');email=String(email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('Enter a valid parent email address.');var suffix=isLocalHost()?'':'?redirect_to='+encodeURIComponent(authRedirect()),r=await authFetch(BASE+'/auth/v1/resend'+suffix,{method:'POST',headers:{'apikey':ANON,'Content-Type':'application/json'},body:JSON.stringify({type:'signup',email:email})},'Resend confirmation');if(!r.ok){var d=null;try{d=await r.json();}catch(e){}throw new Error(authErrorMessage(d,'Could not resend the confirmation email.'));}return{sent:true};}
async function signOut(){var s=session();try{if(s&&s.access_token)await fetch(BASE+'/auth/v1/logout',{method:'POST',headers:{'apikey':ANON,'Authorization':'Bearer '+s.access_token}});}catch(e){}setSession(null);}
async function speak(text){if(!configured())throw new Error('Speech service not configured');var s=session(),url=SPEECH_URL||(BASE+'/functions/v1/sakhi-speech');var h={'apikey':ANON,'Authorization':'Bearer '+((s&&s.access_token)||ANON),'Content-Type':'application/json'};var r=await fetch(url,{method:'POST',headers:h,body:JSON.stringify({text:text})});var mime=(r.headers&&r.headers.get?r.headers.get('content-type'):'')||'';if(!r.ok){var detail='';try{detail=await r.text();}catch(e){}throw new Error('Speech HTTP '+r.status+(detail?' · '+detail.slice(0,180):''));}if(mime&&mime.toLowerCase().indexOf('audio/')!==0)throw new Error('Speech returned unexpected content type '+mime);var bytes=await r.arrayBuffer();if(bytes.byteLength<100)throw new Error('Speech returned an empty audio response');return{bytes:bytes,httpStatus:r.status,mime:mime||'audio/mpeg'};}
window.addEventListener('online',probe);window.addEventListener('offline',function(){verified=false;emit();});
return{state:state,onChange:onChange,enqueue:enqueue,flush:flush,probe:probe,loadSnapshot:loadSnapshot,saveSnapshot:saveSnapshot,syncSnapshot:syncSnapshot,scheduleSnapshot:scheduleSnapshot,speak:speak,request:request,consumeAuthCallback:consumeAuthCallback,signIn:signIn,sendMagicLink:sendMagicLink,signUp:signUp,resendConfirmation:resendConfirmation,signOut:signOut};
})();
