(function(){
'use strict';
const auth=window.ParentAuthService;if(!auth)throw new Error('parent-auth-service.js must load before sakhi-shell.js');
function ensureParentGate(){if(document.getElementById('parentGate'))return;const gate=document.createElement('div');gate.id='parentGate';gate.className='parent-gate hidden';gate.innerHTML=`<div class="parent-gate-card" role="dialog" aria-modal="true" aria-labelledby="parentGateTitle"><button class="parent-close" type="button" aria-label="Close">×</button><div class="parent-lock-icon">🔒</div><h2 id="parentGateTitle">Parents only</h2><p>Enter your parent passcode.</p><input id="parentPasscode" inputmode="numeric" autocomplete="off" maxlength="5" type="password" aria-label="Parent passcode" placeholder="•••••"><button id="parentUnlockBtn" class="btn primary" type="button">Unlock</button><div id="parentGateMsg" class="parent-gate-msg" aria-live="polite"></div></div>`;document.body.appendChild(gate);const close=()=>{gate.classList.add('hidden');gate.querySelector('#parentPasscode').value='';gate.querySelector('#parentGateMsg').textContent=''};gate.querySelector('.parent-close').onclick=close;gate.addEventListener('click',e=>{if(e.target===gate)close()});gate.querySelector('#parentUnlockBtn').onclick=async()=>{const input=gate.querySelector('#parentPasscode'),msg=gate.querySelector('#parentGateMsg');if(!input.value.trim()){msg.textContent='Enter the passcode.';return}if(!await auth.unlock(input.value.trim())){msg.textContent='That passcode did not match.';input.select();return}close();window.go?.('parent')};gate.querySelector('#parentPasscode').addEventListener('keydown',e=>{if(e.key==='Enter')gate.querySelector('#parentUnlockBtn').click()})}
function openParentGate(){ensureParentGate();const gate=document.getElementById('parentGate');gate.classList.remove('hidden');setTimeout(()=>gate.querySelector('#parentPasscode')?.focus(),20)}
async function startAdventureFromGesture(){const button=document.querySelector('.sakhi-start');if(button){button.disabled=true;button.textContent='✨ Getting Sakhi ready…'}try{await window.SpeechService?.initializeFromGesture?.();window.ensureQuest?.();const firstId=(window.data?.quest||[])[0],first=(window.activities||[]).find(a=>a.id===firstId);if(first?.spoken_instruction)void window.SpeechService?.prepare?.(first.spoken_instruction,{kind:'instruction',profile:'sakhi'});const secondId=(window.data?.quest||[])[1],second=(window.activities||[]).find(a=>a.id===secondId);if(second?.spoken_instruction)setTimeout(()=>window.SpeechService?.prepare?.(second.spoken_instruction,{kind:'instruction',profile:'sakhi'}),250);window.go?.('quest')}finally{if(button){button.disabled=false;button.textContent="🌈 START TODAY'S ADVENTURE"}}}
function ensureFamilySyncCard(){const parent=document.getElementById('parent');if(!parent||document.getElementById('familySyncCard'))return;const card=document.createElement('div');card.id='familySyncCard';card.className='card family-sync sakhi-family-sync';card.innerHTML='<h3>☁️ Cloud Progress</h3><p>Checking secure family connection…</p><div class="family-sync-status">Please wait a moment.</div>';parent.querySelector('.parent-lock-row')?.after(card)}
function ensureAudioTest(){const parent=document.getElementById('parent');if(!parent||document.getElementById('parentAudioTest'))return;const card=document.createElement('section');card.id='parentAudioTest';card.className='card';card.innerHTML=`<div class="kicker">Audio check</div><h3>🔊 Test Sakhi Sound</h3><p>Use this if the device seems muted or the browser blocked playback.</p><button class="btn soft" type="button" data-audio-test>TRY SOUND</button><div class="family-sync-status" data-audio-status>Not tested yet.</div>`;const anchor=document.getElementById('familySyncCard')||parent.querySelector('.parent-lock-row');anchor?.after(card);card.querySelector('[data-audio-test]').onclick=async()=>{const s=card.querySelector('[data-audio-status]');s.textContent='Testing…';await window.SpeechService?.initializeFromGesture?.();const ok=await window.SpeechService?.speakInstruction?.("Hi! I'm Sakhi.");const st=window.SpeechService?.getStatus?.()||{};s.textContent=ok?'Sakhi audio started. If you cannot hear it, check device/browser volume or silent settings.':`Audio did not play. Status: ${st.state||'unknown'}. Check device/browser audio settings.`}}
function simplifyHome(){const home=document.getElementById('home');if(!home)return;home.classList.add('sakhi-home');home.querySelectorAll('.section-title,.grid,.priority-grid,.scene-gallery').forEach(el=>el.classList.add('sakhi-secondary-content'));let intro=document.getElementById('sakhiChildHome');if(intro)return;intro=document.createElement('section');intro.id='sakhiChildHome';intro.className='sakhi-child-home';intro.innerHTML=`<div class="sakhi-guide"><div class="sakhi-avatar" aria-hidden="true">✨</div><div><span class="sakhi-kicker">SAKHI MAGIC LEARNING</span><h2>Ready for today's magical adventure?</h2><p>Listen, touch, move, build, discover.</p></div></div><button class="sakhi-start" type="button">🌈 START TODAY'S ADVENTURE</button><div class="sakhi-kingdoms"><button data-kind="reading"><span>📚</span><b>Story Castle</b></button><button data-kind="math"><span>🔢</span><b>Number Kingdom</b></button><button data-kind="logic"><span>🧩</span><b>Puzzle Palace</b></button><button data-kind="science"><span>🔬</span><b>Discovery World</b></button><button data-kind="creativity"><span>🎨</span><b>Create & Play</b></button></div>`;home.prepend(intro);intro.querySelector('.sakhi-start').onclick=startAdventureFromGesture;intro.querySelectorAll('[data-kind]').forEach(button=>button.onclick=()=>{window.go?.('learn');setTimeout(()=>window.openDomain?.(button.dataset.kind),20)})}
function rebrand(){document.title='Sakhi Magic Learning';const apple=document.querySelector('meta[name="apple-mobile-web-app-title"]');if(apple)apple.content='Sakhi Magic Learning';document.querySelectorAll('.nav [data-go="parent"],.bottom [data-go="parent"]').forEach(b=>{b.innerHTML=b.closest('.bottom')?'<span>🔒</span>Parents':'🔒 Parents'});const parentTitle=document.querySelector('#parent .section-title h2');if(parentTitle)parentTitle.textContent='🔒 Parents'}
function installGuard(){window.UIHooks?.on('beforeNavigate',event=>{if(event.args?.[0]!=='parent')return true;if(auth.isUnlocked()){auth.touch();return true}openParentGate();return false})}
function init(){rebrand();ensureParentGate();ensureFamilySyncCard();ensureAudioTest();simplifyHome();installGuard()}
window.openParentGate=openParentGate;window.lockSakhiParent=()=>{auth.lock();window.go?.('home')};window.startAdventureFromGesture=startAdventureFromGesture;window.addEventListener('sakhi-parent-auth-required',openParentGate);window.addEventListener('sakhi-parent-auth-expired',()=>{if(document.getElementById('parent')?.classList.contains('active'))window.go?.('home')});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
