(function(){
'use strict';
const VERSION='2026.09.09-settings-v4';
const CACHE_KEY=window.STORAGE_KEY||'rainbowMagicLearningV2';
const DEFAULTS=Object.freeze({session_length:'AUTO',adventure_mode:'AUTO',preferred_adventure:'AUTO',preferred_characters:[],audio_enabled:true,voice_profile:'sakhi',auto_instructions:true,movement_activities:true,difficulty_preference:'AUTO',learning_focus:'AUTO',extra_reading:false,extra_math:false,reduced_motion:false});
const ALLOWED=Object.freeze({session_length:['AUTO','10','15','20','25'],adventure_mode:['AUTO','MANUAL'],preferred_adventure:['AUTO','meadow','frozen','ocean','story','tower','ballroom'],voice_profile:['sakhi','luna','book','ice','ocean'],difficulty_preference:['AUTO','MORE_SUPPORT','BALANCED','MORE_CHALLENGE'],learning_focus:['AUTO','READING','MATH','WRITING','LOGIC','SCIENCE']});
const BOOLS=new Set(['audio_enabled','auto_instructions','movement_activities','extra_reading','extra_math','reduced_motion']);let state=null;
function clone(v){return JSON.parse(JSON.stringify(v||{}));}
function readRaw(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'{}')}catch(_){return {}}}
function sanitize(input={}){const out={...DEFAULTS};for(const key of Object.keys(DEFAULTS)){if(BOOLS.has(key)){if(typeof input[key]==='boolean')out[key]=input[key];continue}if(key==='preferred_characters'){out[key]=Array.isArray(input[key])?input[key].filter(Boolean).map(String).slice(0,12):[];continue}if(ALLOWED[key]?.includes(String(input[key])))out[key]=String(input[key]);}if(out.adventure_mode==='AUTO')out.preferred_adventure='AUTO';if(out.preferred_adventure!=='AUTO')out.adventure_mode='MANUAL';return out;}
function sourceFromData(){const d=window.data||{},raw=readRaw();return d.settings||d.adaptiveProfile?.settings||raw.settings||raw.adaptiveProfile?.settings||{}}
function mirror(){const d=window.data||{};d.settings=clone(state);d.adaptiveProfile=d.adaptiveProfile||{};d.adaptiveProfile.settings=clone(state);d.settingsVersion=VERSION;}
function refreshFromData(){state=sanitize(sourceFromData());mirror();applyReducedMotion();return clone(state)}
function ensure(){if(!state)refreshFromData();return state}
function all(){return clone(ensure())}function get(key){return ensure()[key]}function sessionMinutes(){const v=get('session_length');return v==='AUTO'?20:Number(v)||20}
async function persist({notify=true,remote=true}={}){mirror();try{window.persist?.(false)}catch(e){console.warn('settings cache persist',e)}if(remote&&window.ProgressService?.status?.().remote){try{await window.ProgressService.saveSettings(all())}catch(e){console.warn('settings remote save',e);window.dispatchEvent(new CustomEvent('sakhi-settings-save-error',{detail:{message:String(e?.message||e)}}));}}if(notify)window.dispatchEvent(new CustomEvent('sakhi-settings-saved',{detail:all()}));}
function set(key,value,{notify=true}={}){if(!(key in DEFAULTS))throw new Error(`Unknown setting: ${key}`);const candidate={...ensure(),[key]:value};if(key==='preferred_adventure')candidate.adventure_mode=String(value)==='AUTO'?'AUTO':'MANUAL';if(key==='adventure_mode'&&String(value)==='AUTO')candidate.preferred_adventure='AUTO';state=sanitize(candidate);applyReducedMotion();if(key==='audio_enabled'&&!state.audio_enabled)window.SpeechService?.stopSpeech?.();void persist({notify});window.dispatchEvent(new CustomEvent('sakhi-setting-changed',{detail:{key,value:state[key],settings:all()}}));if((key==='session_length'||key==='movement_activities')&&!hasCompletedQuestActivity())setTimeout(()=>window.makeQuest?.(),0);return state[key];}
function hasCompletedQuestActivity(){return Object.values((window.data||{}).questResults||{}).some(v=>v!=null)}function isMovement(a){return a?.domain==='gross'||a?.interaction_type==='movement'}function activityMinutes(a){return Math.max(1,Number(a?.estimated_minutes||a?.minutes||3))}
function fitActivities(input=[]){const target=sessionMinutes(),movement=get('movement_activities'),used=new Set(),types=new Set();let list=[...input].filter(Boolean).filter(a=>movement||!isMovement(a));for(const a of list){used.add(a.id);if(a.interaction_type)types.add(a.interaction_type)}const domains=['reading','math','language','logic','science','writing','creativity','memory','executive','knowledge','sel','life'];const total=()=>list.reduce((n,a)=>n+activityMinutes(a),0);function addCandidate(){for(const domain of domains){let a=null;try{a=window.AdaptiveAccelerationService?.recommend?.(domain,{exclude:used,usedTypes:types})||null}catch(_){}if(!a)a=(window.activities||[]).find(x=>x.domain===domain&&x.interaction_type&&!used.has(x.id)&&(movement||!isMovement(x)));if(a&&!used.has(a.id)&&(movement||!isMovement(a))){list.push(a);used.add(a.id);if(a.interaction_type)types.add(a.interaction_type);return true}}return false}while(list.length<3&&addCandidate()){}while(list.length>3&&total()>target+3){const last=list.at(-1);if(total()-activityMinutes(last)<Math.max(8,target*.72))break;used.delete(last.id);list.pop()}while(list.length<9&&total()<target*.86){if(!addCandidate())break}return list;}
function installReducedMotionStyle(){if(document.getElementById('sakhiReducedMotionStyle'))return;const style=document.createElement('style');style.id='sakhiReducedMotionStyle';style.textContent='body[data-reduced-motion="true"] *,body[data-reduced-motion="true"] *::before,body[data-reduced-motion="true"] *::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}';document.head.appendChild(style)}
function applyReducedMotion(){installReducedMotionStyle();if(document.body)document.body.dataset.reducedMotion=String(!!get('reduced_motion'))}
function init(){refreshFromData();applyReducedMotion();if(!hasCompletedQuestActivity())setTimeout(()=>window.makeQuest?.(),0)}
window.addEventListener('sakhi-progress-ready',()=>{refreshFromData();window.AdventureService?.applyCurrent?.();window.SettingsUI?.render?.()});
window.SettingsService=Object.freeze({version:VERSION,defaults:DEFAULTS,allowed:ALLOWED,all,get,set,refreshFromData,sessionMinutes,fitActivities,persist,persistedIn:'learner_settings',effectFor:key=>({session_length:'Controls target quest duration and activity count.',adventure_mode:'Controls whether Sakhi or the parent chooses the visual world.',preferred_adventure:'Changes the presentation world without changing curriculum selection.',audio_enabled:'Enables or suppresses all SpeechService playback.',movement_activities:'Includes or removes gross-motor/movement missions from generated quests.',reduced_motion:'Reduces UI animation and transition motion.'})[key]||'Internal setting; not exposed until behavior is fully wired.'});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
