(function(){
'use strict';
const STATES=Object.freeze({UNINITIALIZED:'UNINITIALIZED',INITIALIZING:'INITIALIZING',READY:'READY',PLAYING:'PLAYING',PAUSED:'PAUSED',BLOCKED_BY_BROWSER:'BLOCKED_BY_BROWSER',DEVICE_MUTED_OR_INAUDIBLE:'DEVICE_MUTED_OR_INAUDIBLE',PROVIDER_ERROR:'PROVIDER_ERROR',PLAYBACK_ERROR:'PLAYBACK_ERROR'});
const blobCache=new Map(),pending=new Map();let state=STATES.UNINITIALIZED,currentAudio=null,lastRequest=null,initialized=false,lastProvider='none';
function log(type,detail={}){window.SakhiRuntimeLog?.log?.(type,detail);window.dispatchEvent(new CustomEvent('sakhi-audio-state',{detail:{state,...detail}}));}
function setState(next,detail={}){state=next;log('AUDIO_STATE',{state,...detail});return state}
function normalizeNarration(text){let s=String(text||'').trim();if(!s)return'';s=s.replace(/\/([a-z])\//gi,(_,p)=>`the ${p.toLowerCase()} sound`);return s.replace(/\s+/g,' ')}
function stopSpeech(){if(currentAudio){try{currentAudio.pause();currentAudio.currentTime=0}catch(_){}currentAudio=null}window.PhonemeAudioService?.stop?.();if(state===STATES.PLAYING||state===STATES.PAUSED)setState(STATES.READY)}
async function initializeFromGesture(){if(initialized)return true;setState(STATES.INITIALIZING);try{const a=new Audio();a.preload='auto';a.muted=true;a.src='data:audio/mp3;base64,//uQZAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAACAAACcQCA';currentAudio=a;try{await a.play();a.pause()}catch(e){if(e?.name==='NotAllowedError'){currentAudio=null;setState(STATES.BLOCKED_BY_BROWSER,{reason:'autoplay_policy'});return false}}currentAudio=null;initialized=true;setState(STATES.READY);return true}catch(e){setState(STATES.PLAYBACK_ERROR,{reason:String(e?.message||e)});return false}}
function cacheKey(text,kind,profile){return `${profile}|${kind}|${text}`}
async function fetchNeural(text,kind,profile){const cfg=window.RAINBOW_CONFIG||{};if(!cfg.ttsEndpoint||!cfg.supabaseAnonKey)throw Object.assign(new Error('Sakhi TTS is not configured'),{stage:'provider'});const key=cacheKey(text,kind,profile);if(blobCache.has(key))return blobCache.get(key);if(pending.has(key))return pending.get(key);const task=(async()=>{const r=await fetch(cfg.ttsEndpoint,{method:'POST',headers:{'content-type':'application/json','apikey':cfg.supabaseAnonKey,'x-client-info':'sakhi-magic-learning/6'},body:JSON.stringify({text,kind,profile})});if(!r.ok){let detail='';try{detail=await r.text()}catch(_){}throw Object.assign(new Error(`Sakhi TTS failed (${r.status}) ${detail.slice(0,160)}`),{stage:'provider',status:r.status})}const type=r.headers.get('content-type')||'';if(!type.includes('audio/'))throw Object.assign(new Error(`Sakhi TTS returned ${type||'unknown content type'}`),{stage:'provider'});const blob=await r.blob();if(blob.size<500)throw Object.assign(new Error('Sakhi TTS returned too little audio'),{stage:'provider'});blobCache.set(key,blob);return blob})().finally(()=>pending.delete(key));pending.set(key,task);return task}
async function prepare(text,{kind='instruction',profile='sakhi'}={}){const clean=normalizeNarration(text);if(!clean)return false;try{await fetchNeural(clean,kind,profile);return true}catch(e){lastProvider='provider-error';setState(STATES.PROVIDER_ERROR,{reason:String(e?.message||e)});return false}}
async function playBlob(blob){stopSpeech();const url=URL.createObjectURL(blob),a=new Audio();a.preload='auto';a.src=url;currentAudio=a;setState(STATES.PLAYING);try{await a.play();return await new Promise(resolve=>{a.onended=()=>{URL.revokeObjectURL(url);if(currentAudio===a)currentAudio=null;setState(STATES.READY);resolve(true)};a.onerror=()=>{URL.revokeObjectURL(url);if(currentAudio===a)currentAudio=null;setState(STATES.PLAYBACK_ERROR,{reason:'media_error'});resolve(false)}})}catch(e){URL.revokeObjectURL(url);if(currentAudio===a)currentAudio=null;setState(e?.name==='NotAllowedError'?STATES.BLOCKED_BY_BROWSER:STATES.PLAYBACK_ERROR,{reason:String(e?.message||e)});return false}}
async function speak(text,{kind='instruction',profile='sakhi'}={}){const clean=normalizeNarration(text);if(!clean)return false;lastRequest={text:clean,kind,profile};if(!initialized&&state===STATES.UNINITIALIZED)setState(STATES.READY,{note:'awaiting-explicit-user-unlock'});try{const blob=await fetchNeural(clean,kind,profile);lastProvider='elevenlabs';const ok=await playBlob(blob);if(!ok&&state===STATES.BLOCKED_BY_BROWSER)log('AUDIO_BLOCKED',{kind});return ok}catch(e){lastProvider='provider-error';setState(STATES.PROVIDER_ERROR,{reason:String(e?.message||e),kind});return false}}
async function speakPhoneme(id){stopSpeech();lastRequest={phoneme:String(id||'')};lastProvider='local-phoneme';const ok=await window.PhonemeAudioService?.play?.(id);if(!ok)log('PHONEME_UNAVAILABLE',{phoneme_id:String(id||'')});return !!ok}
function repeatSpeech(){if(!lastRequest)return Promise.resolve(false);if(lastRequest.phoneme)return speakPhoneme(lastRequest.phoneme);return speak(lastRequest.text,{kind:lastRequest.kind,profile:lastRequest.profile})}
function pause(){if(currentAudio&&!currentAudio.paused){currentAudio.pause();setState(STATES.PAUSED)}}function resume(){if(currentAudio&&currentAudio.paused){setState(STATES.PLAYING);return currentAudio.play().catch(e=>{setState(STATES.PLAYBACK_ERROR,{reason:String(e?.message||e)});return false})}return Promise.resolve(false)}
function getStatus(){return {state,provider:lastProvider,initialized,neuralConfigured:!!window.RAINBOW_CONFIG?.ttsEndpoint,cacheEntries:blobCache.size,phoneme:window.PhonemeAudioService?.getState?.()||'UNAVAILABLE',architecture:'speech-v6-html-media'}}
function attachLifecycle(){window.UIHooks?.on?.('navigate',()=>stopSpeech());window.UIHooks?.on?.('activityOpened',()=>stopSpeech())}
window.SpeechService={states:STATES,initializeFromGesture,prepare,speakInstruction:(t,p='sakhi')=>speak(t,{kind:'instruction',profile:p}),speakCharacter:(t,p='sakhi')=>speak(t,{kind:'character',profile:p}),speakPhoneme,speakWord:(t,p='sakhi')=>speak(t,{kind:'word',profile:p}),speakStory:(t,p='book')=>speak(t,{kind:'story',profile:p}),speakFeedback:(t,p='sakhi')=>speak(t,{kind:'feedback',profile:p}),stopSpeech,repeatSpeech,pause,resume,speak,getStatus,normalizeNarration};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attachLifecycle,{once:true});else attachLifecycle();
})();
