(function(){
'use strict';
const A=window.AssetService;if(!A)throw new Error('asset-service.js must load before visuals.js');
const escapeHtml=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
function hero(){const h=document.querySelector('.hero');if(!h)return;let b=h.querySelector('.hero-visual');if(!b){b=document.createElement('div');b.className='hero-visual';h.appendChild(b)}const pseudo={id:'hero-'+(window.data?.theme||'unicorn'),domain:window.data?.theme==='mermaid'?'science':window.data?.theme==='ice'?'math':'creativity'};b.innerHTML=A.sceneMarkup(pseudo,'hero-scene')+'<div class="hero-sparkles">✦ ⭐ ✨ ★ ✦</div>'}
function gallery(){const g=document.getElementById('themeGallery');if(!g)return;const worlds=Object.entries(A.worlds);g.innerHTML=worlds.map(([key,m])=>`<article class="scene-card">${A.sceneMarkup(key)}<div><b>${escapeHtml(m.title)}</b><small>${escapeHtml(m.purpose)}</small></div></article>`).join('')}
function decorateQuest(){document.querySelectorAll('.quest-card').forEach(c=>{if(c.querySelector('.quest-visual'))return;const activity=(window.activities||[]).find(x=>x.title===c.querySelector('.quest-copy b')?.textContent);if(!activity)return;const b=document.createElement('span');b.className='quest-visual';b.innerHTML=A.sceneMarkup(activity,'quest-scene')+`<span class="quest-icon-badge">${activity.character_icon||activity.icon||'✨'}</span>`;c.querySelector('.quest-icon')?.replaceWith(b)})}
function decorateDomains(){document.querySelectorAll('.domain-card').forEach(c=>{if(c.querySelector('.domain-visual'))return;const domain=(window.domains||[]).find(x=>x.title===c.querySelector('.domain-copy b')?.textContent);if(!domain)return;const b=document.createElement('span');b.className='domain-visual';b.innerHTML=A.sceneMarkup({domain:domain.id},'domain-scene')+`<span class="domain-icon-badge">${domain.icon||'✨'}</span>`;c.querySelector('.domain-icon')?.replaceWith(b)})}
function decorateActivities(){document.querySelectorAll('.activity').forEach(c=>{if(c.querySelector('.activity-visual'))return;const activity=(window.activities||[]).find(x=>x.title===c.querySelector('b')?.textContent);if(!activity)return;const b=document.createElement('span');b.className='activity-visual';b.innerHTML=A.sceneMarkup(activity,'activity-scene');c.prepend(b)})}
function decorateOpenActivity(event){const [activity,containerId]=event.args||[];if(!activity)return;A.preloadForActivity(activity);const host=document.getElementById(containerId),guide=host?.querySelector('.character-guide');if(!guide||host.querySelector('.learning-scene'))return;const world=A.worlds[A.worldFor(activity)];guide.insertAdjacentHTML('afterend',`<div class="learning-scene">${A.sceneMarkup(activity,'learning-scene-art')}<div class="learning-scene-label">✨ ${escapeHtml(world.title)}</div></div>`)}
function insights(){const parent=document.getElementById('parent');if(!parent)return;let box=document.getElementById('learningInsights');if(!box){box=document.createElement('div');box.id='learningInsights';box.className='insight-grid';parent.querySelector('#skillTracker')?.closest('.card')?.after(box)}const used=(window.activities||[]).filter(a=>(window.data?.questHistory||[]).some(x=>x.activityId===a.id)).slice(-6);box.innerHTML=used.length?used.map(a=>{const h=(window.data.questHistory||[]).filter(x=>x.activityId===a.id).slice(-5),last=h.at(-1),avg=h.reduce((n,x)=>n+(Number(x.score)||0),0)/h.length;return `<article class="insight-card ${avg>=.82?'ready':avg>=.65?'practice':'support'}"><span>${a.icon||'✨'} ${escapeHtml(a.skill)}</span><b>${escapeHtml(a.title)}</b><small>Latest ${Math.round((last?.score||0)*100)}% · ${last?.attempts||1} attempt(s) · ${last?.hints||0} hint(s)</small><p>${avg>=.82?'Ready for a varied or slightly harder example.':avg>=.65?'Keep the same skill but change the interaction.':'Use more support before increasing difficulty.'}</p></article>`}).join(''):'<div class="card"><b>No practice history yet.</b><p>Complete a few missions and Sakhi will show evidence-based suggestions here.</p></div>'}
window.VisualUI=Object.freeze({hero,gallery,decorateQuest,decorateDomains,decorateActivities,insights});
window.UIHooks?.on('themeChanged',()=>{hero();gallery()});
window.UIHooks?.on('questRendered',decorateQuest);
window.UIHooks?.on('domainsRendered',decorateDomains);
window.UIHooks?.on('domainOpened',()=>setTimeout(decorateActivities,0));
window.UIHooks?.on('activityOpened',decorateOpenActivity);
window.UIHooks?.on('activitySucceeded',()=>setTimeout(insights,0));
window.UIHooks?.on('activityAttemptFinished',()=>setTimeout(insights,0));
hero();gallery();decorateQuest();decorateDomains();decorateActivities();insights();
})();
