(function(){
'use strict';

const M={
 fairy:['Rainbow Fairy Castle','motivation and transitions','🧚'],unicorn:['Unicorn Rainbow Garden','imagination and story creation','🦄'],ice:['Snow Crystal Castle','listening and memory','❄️'],seasons:['Four Seasons Mountain','weather and compare/contrast','🌦️'],coral:['Coral Reef Adventure','ocean habitats and counting','🐠'],ocean:['Underwater Kingdom','science and observation','🧜‍♀️'],forest:['Forest Friends','animals and categorization','🦊'],reading:['Princess Reading Nook','reading and story language','📚'],cinderella:['Magic Transformation Garden','before/after and sequencing','✨'],ballroom:['Royal Ballroom','movement sequences','💃'],tea:['Royal Tea Garden','counting, manners and sequencing','🫖'],friendship:['Friendship Garden','empathy and kindness','💞']
};
const T={unicorn:['unicorn','fairy','friendship'],ice:['ice','seasons','ballroom'],mermaid:['coral','ocean','fairy'],library:['reading','forest','friendship'],tower:['cinderella','ballroom','reading'],fairy:['fairy','friendship','unicorn'],space:['fairy','unicorn','ice']};
const D={reading:['reading','fairy'],math:['tea','coral'],language:['friendship','reading'],writing:['reading','fairy'],logic:['cinderella','tea'],science:['ocean','coral','forest'],memory:['ice','seasons'],sel:['friendship','tea'],executive:['cinderella','ballroom'],life:['tea','friendship'],creativity:['unicorn','reading'],fine:['fairy','friendship'],gross:['ballroom','ice'],knowledge:['forest','ocean']};
const A={'read-first':'fairy','read-blend':'unicorn','read-cvc':'reading','read-seg':'fairy','math-compose':'coral','math-qty':'seasons','math-pattern':'seasons','math-add':'tea','language-retell':'cinderella','language-why':'friendship','science-float':'ocean','science-shadow':'fairy','memory-directions':'ice','executive-switch':'ballroom','sel-feelings':'friendship','life-cleanup':'cinderella','creativity-story':'unicorn','fine-sort':'fairy','gross-sequence':'ballroom','knowledge-community':'forest'};
const NO=new Set(['read-first','read-blend','read-cvc','read-seg']);
const SCENE_ACCENTS={fairy:['#c8b6ff','#ffafcc'],unicorn:['#bde0fe','#ffc8dd'],ice:['#bde0fe','#e8f7ff'],seasons:['#a8dadc','#ffd166'],coral:['#48cae4','#ff8fab'],ocean:['#00b4d8','#90e0ef'],forest:['#95d5b2','#ffd6a5'],reading:['#cdb4db','#ffe5ec'],cinderella:['#b8c0ff','#f1c0e8'],ballroom:['#ffd6e0','#c8b6ff'],tea:['#ffe5b4','#bde0fe'],friendship:['#ffcad4','#caffbf']};
function e(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function k(a){if(A[a?.id])return A[a.id];const p=D[a?.domain]||['fairy'];let n=0;for(const c of String(a?.id||''))n=(n*31+c.charCodeAt(0))>>>0;return p[n%p.length]}
function sceneMarkup(x,c='scene-art'){const meta=M[x]||M.fairy,[a,b]=SCENE_ACCENTS[x]||SCENE_ACCENTS.fairy;return `<span class="${c} scene-${x}" role="img" aria-label="${e(meta[0])}" style="--scene-a:${a};--scene-b:${b}"><span class="scene-sky"><i></i><i></i><i></i></span><span class="scene-land"></span><span class="scene-castle">🏰</span><span class="scene-star s1">✦</span><span class="scene-star s2">✧</span><span class="scene-character">${meta[2]}</span></span>`}
function hero(){const h=document.querySelector('.hero');if(!h)return;let b=h.querySelector('.hero-visual');if(!b){b=document.createElement('div');b.className='hero-visual';h.appendChild(b)}const x=(T[data?.theme]||T.unicorn)[0];b.innerHTML=sceneMarkup(x,'hero-scene')+'<div class="hero-sparkles">✦ ⭐ ✨ ★ ✦</div>'}
function gallery(){const g=document.getElementById('themeGallery');if(!g)return;const p=T[data?.theme]||T.unicorn;g.innerHTML=p.map(x=>`<article class="scene-card">${sceneMarkup(x)}<div><b>${M[x][0]}</b><small>${M[x][1]}</small></div></article>`).join('')}
function qDecor(){document.querySelectorAll('.quest-card').forEach(c=>{if(c.querySelector('.quest-visual'))return;const a=((typeof activities!=='undefined'&&activities)||[]).find(x=>x.title===c.querySelector('.quest-copy b')?.textContent);if(!a)return;const b=document.createElement('span');b.className='quest-visual';b.innerHTML=sceneMarkup(k(a),'quest-scene')+`<span class="quest-icon-badge">${a.character_icon||a.icon||'✨'}</span>`;c.querySelector('.quest-icon')?.replaceWith(b)})}
function dDecor(){document.querySelectorAll('.domain-card').forEach(c=>{if(c.querySelector('.domain-visual'))return;const d=((typeof domains!=='undefined'&&domains)||[]).find(x=>x.title===c.querySelector('.domain-copy b')?.textContent);if(!d)return;const x=(D[d.id]||['fairy'])[0],b=document.createElement('span');b.className='domain-visual';b.innerHTML=sceneMarkup(x,'domain-scene')+`<span class="domain-icon-badge">${d.icon||'✨'}</span>`;c.querySelector('.domain-icon')?.replaceWith(b)})}
function aDecor(){document.querySelectorAll('.activity').forEach(c=>{if(c.querySelector('.activity-visual'))return;const a=((typeof activities!=='undefined'&&activities)||[]).find(x=>x.title===c.querySelector('b')?.textContent);if(!a)return;const b=document.createElement('span');b.className='activity-visual';b.innerHTML=sceneMarkup(k(a),'activity-scene');c.prepend(b)})}
function scene(a,id){if(!a||NO.has(a.id))return;const c=document.getElementById(id),g=c?.querySelector('.character-guide');if(!g||c.querySelector('.learning-scene'))return;const x=k(a);g.insertAdjacentHTML('afterend',`<div class="learning-scene">${sceneMarkup(x,'learning-scene-art')}<div class="learning-scene-label">✨ ${M[x][0]}</div></div>`)}
window.retryCurrentActivity=()=>{const r=(typeof interactionRuntime!=='undefined'?interactionRuntime:null);if(r&&typeof openStructuredActivity==='function')openStructuredActivity(r.activity,r.containerId,r.source)};
function doneBtns(){const f=document.getElementById('structuredFeedback');if(!f||f.querySelector('.after-mission-actions'))return;f.insertAdjacentHTML('beforeend','<div class="after-mission-actions"><button class="retry-mission" onclick="retryCurrentActivity()">↻ Try Again</button><button class="next-mission" onclick="closeStructuredActivity()">⭐ Back to Quest</button></div>')}
function hist(a){return (data.questHistory||[]).filter(x=>x.activityId===a.id).slice(-8)}
function tip(a){const h=hist(a);if(!h.length)return ['new','Try it first; there is not enough evidence yet.'];const avg=h.reduce((n,x)=>n+(+x.score||0),0)/h.length,at=h.reduce((n,x)=>n+(x.attempts||1),0)/h.length,hi=h.reduce((n,x)=>n+(x.hints||0),0)/h.length;if(avg>=.88&&at<1.8&&hi<.6)return ['ready','Strong and efficient. Try a harder example or a different interaction format next.'];if(avg>=.68)return ['practice','Good learning zone. Keep the skill, change the game, and ask her to explain how she knows.'];if(at>=2.5||hi>=1.5)return ['support','Reduce one difficulty step, model one example, then retry with stronger scaffolding.'];return ['support','Repeat this skill in a different format before adding new content.']}
function insights(){const p=document.getElementById('parent');if(!p)return;let b=document.getElementById('learningInsights');if(!b){const t=document.createElement('div');t.className='section-title';t.innerHTML='<h2>📊 Learning Coach Analysis</h2><p>Uses attempts, hints and recent success—not only stars.</p>';b=document.createElement('div');b.id='learningInsights';b.className='insight-grid';p.querySelector('#skillTracker')?.closest('.card')?.after(t,b)}if(!b)return;const l=((typeof activities!=='undefined'&&activities)||[]).filter(a=>hist(a).length).slice(-6);b.innerHTML=l.length?l.map(a=>{const h=hist(a),z=h[h.length-1],r=tip(a);return `<div class="insight-card ${r[0]}"><span>${a.icon||'✨'} ${e(a.skill)}</span><b>${e(a.title)}</b><small>Latest: ${Math.round((z.score||0)*100)}% · attempts ${z.attempts||1} · hints ${z.hints||0}</small><p>${r[1]}</p><button onclick="go('learn');setTimeout(()=>runLearningActivity('${a.id}'),60)">Practice this skill ↻</button></div>`}).join(''):'<div class="card"><b>No practice history yet.</b><p>Complete a few missions and the app will suggest what to repeat, strengthen, or extend.</p></div>'}
if(typeof setTheme==='function'){const old=setTheme;window.setTheme=v=>{old(v);hero();gallery()}}
if(typeof renderQuest==='function'){const old=renderQuest;window.renderQuest=()=>{old();qDecor()}}
if(typeof renderDomains==='function'){const old=renderDomains;window.renderDomains=()=>{old();dDecor()}}
if(typeof openDomain==='function'){const old=openDomain;window.openDomain=v=>{old(v);setTimeout(aDecor,0)}}
if(typeof openStructuredActivity==='function'){const old=openStructuredActivity;window.openStructuredActivity=(a,id,src)=>{old(a,id,src);scene(a,id);const t=document.querySelector(`#${id} .child-tools`);if(t&&!t.querySelector('.start-over'))t.insertAdjacentHTML('beforeend','<button class="child-tool start-over" onclick="retryCurrentActivity()">↻ Start Over</button>')}}
if(typeof finishSuccess==='function'){const old=finishSuccess;window.finishSuccess=v=>{old(v);setTimeout(()=>{doneBtns();insights()},0)}}
if(typeof finishAttempt==='function'){const old=finishAttempt;window.finishAttempt=v=>{old(v);setTimeout(()=>{doneBtns();insights()},0)}}
((typeof activities!=='undefined'&&activities)||[]).forEach(a=>a.visual_policy=NO.has(a.id)?'no-answer-clue':'context-support');
hero();gallery();qDecor();dDecor();aDecor();insights();
})();