const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..');
const audio=fs.readFileSync(path.join(root,'sakhi-audio.js'),'utf8');
for(const token of ['af_heart','NATURAL_SPEED=.86','loadNarrationManifest','fetchLocalPart','kokoro-local','speakServerPart','naturalSpeak','describeQuestion','startKeepAlive','prepare:loadNaturalVoice'])if(!audio.includes(token))throw new Error('Bundled cross-device voice path is incomplete: '+token);
if(/speechSynthesis|SpeechSynthesisUtterance|apple-system|speakApplePart/.test(audio))throw new Error('Robotic browser speech must not exist in the Sakhi narration path');
if(!/naturalMode:'kokoro-local-first'/.test(audio)||!/if\(APPLE_MOBILE\)throw new Error\('This line is not in the instant iPad narration pack\.'/ .test(audio)||/NATURAL_IMPORT|KokoroTTS|from_pretrained|tts\.generate/.test(audio))throw new Error('iPad must use bundled Kokoro without waiting for a server or loading a browser model');
if(/SakhiCloud\.speak\(/.test(audio))throw new Error('Narration must not depend on the exhausted paid speech provider');
const entry=fs.readFileSync(path.join(root,'scripts/kokoro-browser-entry.js'),'utf8');
if(!/numThreads\s*=\s*1/.test(entry)||!/proxy\s*=\s*false/.test(entry))throw new Error('The iPad-safe single-thread runtime is not configured');
console.log('Voice gate passed: bundled Kokoro af_heart starts locally on iPad without a browser model or robotic browser voice.');
