const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..');
const audio=fs.readFileSync(path.join(root,'sakhi-audio.js'),'utf8');
for(const token of ['./vendor/kokoro-runtime.js','KokoroTTS.from_pretrained','af_heart','NATURAL_SPEED=.86','SAKHI_TTS_URL','kokoro-server','speakServerPart','naturalSpeak','describeQuestion','startKeepAlive','prepare:loadNaturalVoice'])if(!audio.includes(token))throw new Error('Free cross-device voice path is incomplete: '+token);
if(/speechSynthesis|SpeechSynthesisUtterance|apple-system|speakApplePart/.test(audio))throw new Error('Robotic browser speech must not exist in the Sakhi narration path');
if(!/naturalMode:APPLE_MOBILE\?'kokoro-server':'kokoro-local'/.test(audio))throw new Error('Apple devices must use server-side Kokoro');
if(/SakhiCloud\.speak\(/.test(audio))throw new Error('Narration must not depend on the exhausted paid speech provider');
const entry=fs.readFileSync(path.join(root,'scripts/kokoro-browser-entry.js'),'utf8');
if(!/numThreads\s*=\s*1/.test(entry)||!/proxy\s*=\s*false/.test(entry))throw new Error('The iPad-safe single-thread runtime is not configured');
console.log('Voice gate passed: detailed Kokoro remains local on desktop and uses server-side af_heart on iOS, with no robotic browser voice.');
